'use client';

/* eslint-disable @next/next/no-img-element */

import { type KeyboardEvent as ReactKeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { LeadModal } from '@/app/lead-modal';

type Language = 'ru' | 'uz' | 'en';
type Mode = 'cards' | 'chess';
type Sort = 'priceAsc' | 'priceDesc' | 'areaAsc' | 'areaDesc' | 'floorAsc' | 'roomsAsc';
type Unit = { id: string; number: string; rooms: number; area: number; price: number; oldPrice: number | null; pricePerM2: number; currency: string; phase: string; floor: number; maxFloor: number; entrance: string; completion: string; plan: string; planSource: string; status: 'available'; promotion: boolean };
export type VohaSnapshot = { project: string; source: string; sourceLanding: string; sourceProjectUuid: string; capturedAt: string; officialTotalAtCapture: number; currency: string; selectionMethod: string; units: Unit[] };

const appBasePath = process.env.NEXT_PUBLIC_APP_BASE_PATH ?? '';
const languages: Language[] = ['ru', 'uz', 'en'];
const copy = {
  ru: {
    back: 'О проекте', project: 'VOHA · PRIVATE WATERSIDE CLUB', title: 'Выберите пространство', accent: 'для тихой жизни.', lead: 'Полный сохранённый срез официального каталога — без реконструкции снятых, проданных или забронированных позиций.',
    modes: { cards: 'Карточки', chess: 'Шахматка' }, modeLabel: 'Режим каталога', language: 'Язык', snapshot: 'Официальный snapshot', captured: 'Срез каталога', offers: 'предложения', filters: 'Фильтры', phase: 'Очередь', allPhases: 'Все очереди', phaseOne: 'I очередь · сдана', phaseTwo: 'II очередь · III кв. 2027', rooms: 'Комнаты', allRooms: 'Все', areaFrom: 'Площадь от', areaTo: 'Площадь до', floor: 'Этаж', allFloors: 'Все', priceFrom: 'Цена от, млрд', priceTo: 'Цена до, млрд', status: 'Статус', available: 'В продаже', sort: 'Сортировка', reset: 'Сбросить', results: 'предложений',
    sorts: { priceAsc: 'Сначала дешевле', priceDesc: 'Сначала дороже', areaAsc: 'Площадь по возрастанию', areaDesc: 'Площадь по убыванию', floorAsc: 'Сначала нижние этажи', roomsAsc: 'Сначала меньше комнат' },
    sourceNote: 'Все 104 предложения загружены из официального каталога 30 августа 2026 года. Цены, акции и статусы фиксируются на дату snapshot и могут измениться.', active: 'В продаже', apartment: 'комн.', entrance: 'подъезд', price: 'Цена на дату snapshot', oldPrice: 'Цена до акции', perM2: 'за м²', completion: 'Срок в каталоге', plan: 'Увеличить планировку', choose: 'Выбрать квартиру', showMore: 'Показать ещё', noResults: 'По этим параметрам предложений нет.', resetFilters: 'Сбросить фильтры', previous: 'Прокрутить влево', next: 'Прокрутить вправо', matrix: 'Опубликованные предложения', selected: 'Выбранная квартира', close: 'Закрыть', consult: 'Получить консультацию', mobileHint: 'Проведите пальцем по таблице или используйте стрелки.',
    formName: 'Ваше имя', formPhone: 'Номер телефона', formSubmit: 'Сохранить запрос', formNameError: 'Введите имя — не менее 2 символов.', formPhoneError: 'Введите 9 цифр после +998.', formSuccess: 'Спасибо. Контекст квартиры сохранён; тестовая отправка лида не выполнялась.', disclaimer: 'Snapshot не является публичной офертой.',
  },
  uz: {
    back: 'Loyiha haqida', project: 'VOHA · PRIVATE WATERSIDE CLUB', title: 'Sokin hayot uchun', accent: 'makon tanlang.', lead: 'Rasmiy katalogning to‘liq saqlangan kesimi — olingan, sotilgan yoki band joylar qayta yaratilmagan.',
    modes: { cards: 'Kartalar', chess: 'Shaxmatka' }, modeLabel: 'Katalog ko‘rinishi', language: 'Til', snapshot: 'Rasmiy snapshot', captured: 'Katalog kesimi', offers: 'taklif', filters: 'Filtrlar', phase: 'Navbat', allPhases: 'Barcha navbatlar', phaseOne: 'I navbat · topshirilgan', phaseTwo: 'II navbat · 2027-yil III chorak', rooms: 'Xonalar', allRooms: 'Barchasi', areaFrom: 'Maydon, dan', areaTo: 'Maydon, gacha', floor: 'Qavat', allFloors: 'Barchasi', priceFrom: 'Narx, mlrd dan', priceTo: 'Narx, mlrd gacha', status: 'Holat', available: 'Sotuvda', sort: 'Saralash', reset: 'Tozalash', results: 'taklif',
    sorts: { priceAsc: 'Arzonidan boshlab', priceDesc: 'Qimmatidan boshlab', areaAsc: 'Maydon o‘sishi bo‘yicha', areaDesc: 'Maydon kamayishi bo‘yicha', floorAsc: 'Quyi qavatlar avval', roomsAsc: 'Kam xonadan boshlab' },
    sourceNote: '104 taklifning barchasi 2026-yil 30-avgustda rasmiy katalogdan yuklangan. Narx, aksiya va holat snapshot sanasiga tegishli.', active: 'Sotuvda', apartment: 'xonali', entrance: 'kirish', price: 'Snapshot sanasidagi narx', oldPrice: 'Aksiyagacha narx', perM2: 'm² uchun', completion: 'Katalogdagi muddat', plan: 'Rejani kattalashtirish', choose: 'Xonadon tanlash', showMore: 'Yana ko‘rsatish', noResults: 'Bu parametrlar bo‘yicha taklif yo‘q.', resetFilters: 'Filtrlarni tozalash', previous: 'Chapga surish', next: 'O‘ngga surish', matrix: 'E’lon qilingan takliflar', selected: 'Tanlangan xonadon', close: 'Yopish', consult: 'Maslahat olish', mobileHint: 'Jadvalni barmoq bilan suring yoki strelkalardan foydalaning.',
    formName: 'Ismingiz', formPhone: 'Telefon raqami', formSubmit: 'So‘rovni saqlash', formNameError: 'Kamida 2 ta belgi kiriting.', formPhoneError: '+998 dan keyin 9 ta raqam kiriting.', formSuccess: 'Rahmat. Xonadon konteksti saqlandi; test lead yuborilmadi.', disclaimer: 'Snapshot ommaviy oferta emas.',
  },
  en: {
    back: 'About the project', project: 'VOHA · PRIVATE WATERSIDE CLUB', title: 'Choose a space', accent: 'for quiet living.', lead: 'The complete saved official-catalogue snapshot, without reconstructing withdrawn, sold or reserved inventory.',
    modes: { cards: 'Cards', chess: 'Matrix' }, modeLabel: 'Catalogue view', language: 'Language', snapshot: 'Official snapshot', captured: 'Catalogue snapshot', offers: 'listings', filters: 'Filters', phase: 'Phase', allPhases: 'All phases', phaseOne: 'Phase I · completed', phaseTwo: 'Phase II · Q3 2027', rooms: 'Rooms', allRooms: 'All', areaFrom: 'Area from', areaTo: 'Area to', floor: 'Floor', allFloors: 'All', priceFrom: 'Price from, bn', priceTo: 'Price to, bn', status: 'Status', available: 'For sale', sort: 'Sort', reset: 'Reset', results: 'listings',
    sorts: { priceAsc: 'Lowest price first', priceDesc: 'Highest price first', areaAsc: 'Area ascending', areaDesc: 'Area descending', floorAsc: 'Lower floors first', roomsAsc: 'Fewer rooms first' },
    sourceNote: 'All 104 listings were loaded from the official catalogue on 30 August 2026. Prices, promotions and statuses are fixed at snapshot date and may change.', active: 'For sale', apartment: 'room', entrance: 'entrance', price: 'Price at snapshot date', oldPrice: 'Pre-offer price', perM2: 'per m²', completion: 'Catalogue completion', plan: 'Enlarge plan', choose: 'Choose apartment', showMore: 'Show more', noResults: 'No listings match these filters.', resetFilters: 'Reset filters', previous: 'Scroll left', next: 'Scroll right', matrix: 'Published listings', selected: 'Selected apartment', close: 'Close', consult: 'Request a consultation', mobileHint: 'Swipe the table or use the arrow controls.',
    formName: 'Your name', formPhone: 'Phone number', formSubmit: 'Save request', formNameError: 'Enter at least 2 characters.', formPhoneError: 'Enter 9 digits after +998.', formSuccess: 'Thank you. Apartment context was saved; no test lead was sent.', disclaimer: 'The snapshot is not a public offer.',
  },
} as const;

function asset(path: string) { return `${appBasePath}${path}`; }
function withLanguage(path: string, language: Language) { return `${appBasePath}${path}?lang=${language}`; }
function money(value: number, language: Language) { return `${new Intl.NumberFormat(language === 'ru' ? 'ru-RU' : language === 'uz' ? 'uz-UZ' : 'en-US').format(value)} UZS`; }
function leadSubmitUrl() { return `${appBasePath}/v1/leads`; }

function useLanguage(initialLanguage: Language = 'ru') {
  const [language, setLanguageState] = useState<Language>(initialLanguage);
  useEffect(() => { const query = new URLSearchParams(window.location.search).get('lang'); const saved = localStorage.getItem('voha-language'); const next = languages.includes(query as Language) ? query : saved; const frame = requestAnimationFrame(() => { if (languages.includes(next as Language)) setLanguageState(next as Language); }); return () => cancelAnimationFrame(frame); }, []);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem('voha-language', next); const url = new URL(location.href); url.searchParams.set('lang', next); history.replaceState({}, '', url); };
  return [language, setLanguage] as const;
}

function PlanButton({ unit, label, onOpen }: { unit: Unit; label: string; onOpen: () => void }) { return <button className="voha-unit-plan" type="button" onClick={onOpen} aria-label={`${label} № ${unit.number}`}><img src={asset(unit.plan)} alt={`Voha · № ${unit.number}`} loading="lazy" decoding="async" /><span aria-hidden="true">↗</span></button>; }

function PlanLightbox({ unit, language, onClose }: { unit: Unit; language: Language; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null); const t = copy[language];
  useEffect(() => { closeRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [onClose]);
  return <div className="voha-plan-lightbox" role="dialog" aria-modal="true" aria-label={`${t.plan} № ${unit.number}`} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><button ref={closeRef} type="button" onClick={onClose} aria-label={t.close}>×</button><figure><img src={asset(unit.plan)} alt={`Планировка Voha № ${unit.number}`} /><figcaption><strong>№ {unit.number} · {unit.rooms} {t.apartment} · {unit.area.toFixed(2)} м²</strong><span>{unit.floor}/{unit.maxFloor} · {t.phase} {unit.phase}</span></figcaption></figure></div>;
}

function Consultation({ unit, language, onClose }: { unit: Unit; language: Language; onClose: () => void }) {
  const t = copy[language];
  const context = `projectSlug=voha;lang=${language};surface=catalog:unit;unitUuid=${unit.id};number=${unit.number};phase=${unit.phase};floor=${unit.floor}/${unit.maxFloor};rooms=${unit.rooms};area=${unit.area};price=${unit.price}`;
  return <LeadModal open language={language} context={context} brandName="NRG-BI" projectName="VOHA" tagline={`№ ${unit.number} · ${unit.rooms} · ${unit.area.toFixed(2)} m²`} facts={[`${unit.floor}/${unit.maxFloor} ${t.floor}`, `${t.phase} ${unit.phase}`, money(unit.price, language)]} submitUrl={leadSubmitUrl()} projectSlug="voha" unitId={unit.id} privacyUrl={`${appBasePath}/privacy?project=voha&lang=${language}&from=catalog`} requireConsent onClose={onClose} />;
}

function Detail({ unit, language, onPlan, onLead }: { unit: Unit; language: Language; onPlan: () => void; onLead: () => void }) {
  const t = copy[language]; return <aside className="voha-unit-detail" aria-label={t.selected}><header><small>{t.selected}</small><strong>№ {unit.number}</strong><span>{t.active}</span></header><PlanButton unit={unit} label={t.plan} onOpen={onPlan} /><h3>{unit.rooms} {t.apartment} · {unit.area.toFixed(2)} м²</h3><dl><div><dt>{t.phase}</dt><dd>{unit.phase}</dd></div><div><dt>{t.floor}</dt><dd>{unit.floor}/{unit.maxFloor}</dd></div><div><dt>{t.entrance}</dt><dd>{unit.entrance}</dd></div></dl><div className="voha-unit-detail__price"><small>{t.price}</small><strong>{money(unit.price, language)}</strong><span>{money(unit.pricePerM2, language)} {t.perM2}</span>{unit.oldPrice ? <del>{money(unit.oldPrice, language)}</del> : null}</div><button type="button" onClick={onLead}>{t.consult}<span>↗</span></button></aside>;
}

export function VohaCatalog({ snapshot, initialLanguage = 'ru' }: { snapshot: VohaSnapshot; initialLanguage?: Language }) {
  const [language, setLanguage] = useLanguage(initialLanguage); const t = copy[language]; const [mode, setMode] = useState<Mode>('cards'); const [phase, setPhase] = useState('all'); const [rooms, setRooms] = useState('all'); const [areaFrom, setAreaFrom] = useState(''); const [areaTo, setAreaTo] = useState(''); const [floor, setFloor] = useState('all'); const [priceFrom, setPriceFrom] = useState(''); const [priceTo, setPriceTo] = useState(''); const [sort, setSort] = useState<Sort>('priceAsc'); const [visible, setVisible] = useState(12); const [selectedId, setSelectedId] = useState(snapshot.units[0]?.id); const [plan, setPlan] = useState<Unit>(); const [lead, setLead] = useState<Unit>(); const scrollRef = useRef<HTMLDivElement>(null);
  const roomOptions = useMemo(() => [...new Set(snapshot.units.map((unit) => unit.rooms))].sort((a, b) => a - b), [snapshot.units]); const floors = useMemo(() => [...new Set(snapshot.units.map((unit) => unit.floor))].sort((a, b) => a - b), [snapshot.units]);
  const filtered = useMemo(() => {
    const minArea = Number(areaFrom) || 0; const maxArea = Number(areaTo) || Infinity; const minPrice = (Number(priceFrom) || 0) * 1e9; const maxPrice = (Number(priceTo) || Infinity) * 1e9;
    return snapshot.units.filter((unit) => (phase === 'all' || unit.phase === phase) && (rooms === 'all' || unit.rooms === Number(rooms)) && (floor === 'all' || unit.floor === Number(floor)) && unit.area >= minArea && unit.area <= maxArea && unit.price >= minPrice && unit.price <= maxPrice).sort((a, b) => sort === 'priceAsc' ? a.price - b.price : sort === 'priceDesc' ? b.price - a.price : sort === 'areaAsc' ? a.area - b.area : sort === 'areaDesc' ? b.area - a.area : sort === 'floorAsc' ? a.floor - b.floor || a.rooms - b.rooms : a.rooms - b.rooms || a.area - b.area);
  }, [snapshot.units, phase, rooms, areaFrom, areaTo, floor, priceFrom, priceTo, sort]);
  const matrixFloors = useMemo(() => [...new Set(filtered.map((unit) => unit.floor))].sort((a, b) => b - a), [filtered]); const selected = filtered.find((unit) => unit.id === selectedId) ?? filtered[0];
  const reset = () => { setPhase('all'); setRooms('all'); setAreaFrom(''); setAreaTo(''); setFloor('all'); setPriceFrom(''); setPriceTo(''); setSort('priceAsc'); setVisible(12); };
  const scroll = (direction: number) => scrollRef.current?.scrollBy({ left: direction * Math.min(scrollRef.current.clientWidth * .82, 680), behavior: 'smooth' }); const onMatrixKey = (event: ReactKeyboardEvent<HTMLDivElement>) => { if (event.key === 'ArrowLeft') scroll(-1); if (event.key === 'ArrowRight') scroll(1); };
  const captured = new Intl.DateTimeFormat(language === 'ru' ? 'ru-RU' : language === 'uz' ? 'uz-UZ' : 'en-GB', { dateStyle: 'long', timeZone: 'Asia/Tashkent' }).format(new Date(snapshot.capturedAt));
  return <main className="voha-catalog" lang={language}>
    <header className="voha-catalog-header"><a className="voha-catalog-wordmark" href={withLanguage('/voha', language)}>VOHA<small>by NRG-BI</small></a><a className="voha-catalog-back" href={withLanguage('/voha', language)}>← {t.back}</a><div aria-label={t.language}>{languages.map((item) => <button type="button" key={item} className={language === item ? 'is-active' : ''} onClick={() => setLanguage(item)} aria-pressed={language === item}>{item.toUpperCase()}</button>)}</div></header>
    <section className="voha-catalog-hero"><div><p>{t.project}</p><h1>{t.title}<em>{t.accent}</em></h1><span>{t.lead}</span></div><aside><small>{t.snapshot}</small><strong>{captured}</strong><span>{snapshot.units.length} / {snapshot.officialTotalAtCapture} {t.offers}</span></aside></section>
    <section className="voha-catalog-controls" aria-label={t.filters}><div className="voha-mode-switch" role="radiogroup" aria-label={t.modeLabel}>{(['cards', 'chess'] as Mode[]).map((item) => <button data-testid={`voha-mode-${item}`} key={item} type="button" role="radio" aria-checked={mode === item} className={mode === item ? 'is-active' : ''} onClick={() => setMode(item)}>{t.modes[item]}</button>)}</div><div className="voha-filters"><label><span>{t.phase}</span><select value={phase} onChange={(event) => setPhase(event.target.value)}><option value="all">{t.allPhases}</option><option value="1">{t.phaseOne}</option><option value="2">{t.phaseTwo}</option></select></label><label><span>{t.rooms}</span><select value={rooms} onChange={(event) => setRooms(event.target.value)}><option value="all">{t.allRooms}</option>{roomOptions.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label><span>{t.areaFrom}</span><input type="number" min="0" inputMode="decimal" placeholder="44" value={areaFrom} onChange={(event) => setAreaFrom(event.target.value)} /></label><label><span>{t.areaTo}</span><input type="number" min="0" inputMode="decimal" placeholder="163" value={areaTo} onChange={(event) => setAreaTo(event.target.value)} /></label><label><span>{t.floor}</span><select value={floor} onChange={(event) => setFloor(event.target.value)}><option value="all">{t.allFloors}</option>{floors.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label><span>{t.priceFrom}</span><input type="number" min="0" step=".1" inputMode="decimal" placeholder="1.2" value={priceFrom} onChange={(event) => setPriceFrom(event.target.value)} /></label><label><span>{t.priceTo}</span><input type="number" min="0" step=".1" inputMode="decimal" placeholder="5.2" value={priceTo} onChange={(event) => setPriceTo(event.target.value)} /></label><label><span>{t.status}</span><select value="available" disabled><option value="available">{t.available}</option></select></label><button type="button" onClick={reset}>{t.reset} ↺</button></div></section>
    <section className="voha-catalog-results"><header><div><strong>{filtered.length}</strong><span>{t.results}</span></div><label><span>{t.sort}</span><select value={sort} onChange={(event) => setSort(event.target.value as Sort)}>{Object.entries(t.sorts).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></header><div className="voha-catalog-source"><span>i</span><p>{t.sourceNote}</p></div>
      {!filtered.length ? <div className="voha-catalog-empty"><h2>{t.noResults}</h2><button type="button" onClick={reset}>{t.resetFilters}</button></div> : null}
      {mode === 'cards' && filtered.length ? <><div className="voha-unit-grid">{filtered.slice(0, visible).map((unit) => <article className="voha-unit-card" key={unit.id}><header><span>{t.phase} {unit.phase}</span><span>{t.active}</span></header><PlanButton unit={unit} label={t.plan} onOpen={() => setPlan(unit)} /><div className="voha-unit-card__body"><small>VOHA · № {unit.number}</small><h2>{unit.rooms} {t.apartment} · {unit.area.toFixed(2)} м²</h2><p>{unit.floor}/{unit.maxFloor} {t.floor} · {unit.entrance} {t.entrance} · {unit.completion}</p><div><small>{t.price}</small><strong>{money(unit.price, language)}</strong><span>{money(unit.pricePerM2, language)} {t.perM2}</span>{unit.oldPrice ? <del>{t.oldPrice}: {money(unit.oldPrice, language)}</del> : null}</div><button type="button" onClick={() => setLead(unit)}>{t.choose}<span>↗</span></button></div></article>)}</div>{visible < filtered.length ? <button className="voha-load-more" type="button" onClick={() => setVisible((count) => count + 12)}>{t.showMore}<span>{Math.min(visible, filtered.length)} / {filtered.length}</span></button> : null}</> : null}
      {mode === 'chess' && filtered.length ? <section className="voha-matrix"><header><div><small>VOHA</small><h2>{t.matrix}</h2><p>{t.mobileHint}</p></div><div><button data-testid="voha-scroll-left" type="button" onClick={() => scroll(-1)} aria-label={t.previous}>←</button><button data-testid="voha-scroll-right" type="button" onClick={() => scroll(1)} aria-label={t.next}>→</button></div></header><div className="voha-matrix-detail"><div ref={scrollRef} className="voha-matrix-scroll" tabIndex={0} onKeyDown={onMatrixKey} aria-label={t.matrix}><div className="voha-matrix-table"><div className="voha-matrix-caption"><span>{t.floor}</span><strong>{t.offers}</strong></div>{matrixFloors.map((value) => <div className="voha-matrix-row" key={value}><div className="voha-matrix-floor"><strong>{value}</strong><span>{t.floor}</span></div><div className="voha-matrix-cells">{filtered.filter((unit) => unit.floor === value).sort((a, b) => Number.parseInt(a.number) - Number.parseInt(b.number)).map((unit) => <button type="button" key={unit.id} className={selected?.id === unit.id ? 'is-selected' : ''} aria-pressed={selected?.id === unit.id} onClick={() => setSelectedId(unit.id)}><small>№ {unit.number}</small><strong>{unit.rooms} · {unit.area.toFixed(1)} м²</strong><span>{money(unit.price, language)}</span></button>)}</div></div>)}</div></div>{selected ? <Detail unit={selected} language={language} onPlan={() => setPlan(selected)} onLead={() => setLead(selected)} /> : null}</div></section> : null}
    </section>
    <footer className="voha-catalog-footer"><a className="voha-catalog-wordmark" href={withLanguage('/voha', language)}>VOHA<small>by NRG-BI</small></a><p>{t.disclaimer}</p><a href={`${appBasePath}/privacy?project=voha&lang=${language}&from=catalog`}>{language === 'ru' ? 'Обработка данных' : language === 'uz' ? 'Ma’lumotlarni qayta ishlash' : 'Data processing'}</a><a href="tel:1360">1360</a></footer>{plan ? <PlanLightbox unit={plan} language={language} onClose={() => setPlan(undefined)} /> : null}{lead ? <Consultation unit={lead} language={language} onClose={() => setLead(undefined)} /> : null}
  </main>;
}
