'use client';

/* eslint-disable @next/next/no-img-element */

import { useRouter } from 'next/navigation';
import {
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent,
  type TouchEvent as ReactTouchEvent,
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react';
import { LeadModal } from '@/app/lead-modal';
import { botanikaLeadSubmitUrl } from './botanika-lead';

type Language = 'ru' | 'uz' | 'en';
type SlideKind = 'photo' | 'render' | 'scheme' | 'composite' | 'archive';
type Slide = { src: string; kind: SlideKind };

const appBasePath = process.env.NEXT_PUBLIC_APP_BASE_PATH ?? '';
const languages: Language[] = ['ru', 'uz', 'en'];
const panorama = 'https://uzbekistan360.uz/ru/location/botanikaKxa';
const mapUrl = 'https://www.google.com/maps/search/?api=1&query=41.349876,69.330564';

const copy = {
  ru: {
    skip: 'К содержанию', menu: 'Открыть навигацию', closeMenu: 'Закрыть навигацию', navigation: 'Навигация', language: 'Язык',
    nav: ['Полевые заметки', 'Архитектура', 'Живая коллекция', 'Двор', 'Холлы', 'Локация'], catalogue: 'Индекс резиденций', consult: 'Получить консультацию',
    eyebrow: 'BOTANIKA SAROYI · БИЗНЕС-КЛАСС · ТАШКЕНТ', heroTitle: 'Живой атлас', heroAccent: 'дома.', heroText: 'Архитектура, двор и зрелая зелень — в реальных фотографиях уже выполненных частей проекта.', heroLabel: 'Plate 01 · Реальная фотография', heroAlt: 'Реальная фотография фасадов выполненной части Botanika Saroyi', heroNote: 'Мирзо-Улугбекский район · рядом с Ботаническим садом',
    manifestTop: 'Field note · 00', manifestTitle: 'Дом читается по фактам, не по обещаниям.', manifestText: 'Botanika Saroyi — бизнес-класс рядом с Ботаническим садом. Фактическая съёмка, официальные концепты и архив стройки разделены, поэтому каждый визуальный материал сохраняет свой настоящий статус.',
    facts: [['Бизнес', 'официальный класс'], ['16', 'этажей'], ['от 3 м', 'высота потолков'], ['45%+', 'территории — озеленение'], ['IV кв. 2026', 'ближайшая сдача']],
    architectureTop: 'Plate 02 · Архитектура', architectureTitle: 'Limestone, металл и восточный ритм.', architectureText: 'Фактические фасады показаны отдельно от официальной визуализации. Орнамент встроен в архитектуру как ритм, а не как декор поверх неё.', facadeCaptions: ['Фасад и натуральный камень', 'Архитектура со стороны двора', 'Фасад выполненной части проекта'], renderTitle: 'Архитектурная концепция', renderText: 'Официальный рендер раскрывает замысел материалов и композиции. Это проектное изображение, а не фотография текущего состояния.',
    materialsTop: 'Material ledger · 01–05', materialsTitle: 'Материалы как конструкция характера.', materials: [['Каркас', 'Монолитный железобетон'], ['Межквартирные стены', 'Керамическая кладка 250 мм'], ['Камень', 'Натуральный limestone'], ['Фасад', 'Алюминиевые композитные панели'], ['Остекление', 'Трёхкамерный профиль · мультифункциональный стеклопакет']],
    botanyTop: 'Specimen index · 45%+', botanyTitle: 'Живая коллекция вместо фонового озеленения.', botanyText: 'Фотографии показывают реальный ландшафт проекта, а индекс фиксирует заявленный состав посадок.',
    plants: [['Деревья', 'слива · сосна · ель колючая · лириодендрон · рябина · клён · липа · катальпа · сосна чёрная и горная'], ['Хвойные', 'кипарис · туя · можжевельник · самшит'], ['Кустарники', 'барбарис · бересклет · нандина · бирючина · пузыреплодник · вейгела · калина · лавровишня · сирень · кизильник · фотиния · спирея'], ['Цветущие', 'лаванда · герань · розы · гортензии · лилейник · седум'], ['Травы', 'пеннисетум']], landscapePhoto: 'Реальная фотография озеленения проекта',
    courtyardTop: 'Plate 03 · Двор уже существует', courtyardTitle: 'Без машин. С зеленью. Для разных ритмов дня.', courtyardText: 'Закрытая территория, круглосуточное видеонаблюдение, детская площадка из экоматериалов, BBQ, качели и тихие зоны заявлены в материалах проекта. Здесь — только фактическая фотосерия двора.', courtyardCaptions: ['Существующий озеленённый двор', 'Площадка и зоны отдыха', 'Двор без машин', 'Тихая зона среди зелени'], courtyardFacts: ['Закрытая территория', 'Видеонаблюдение 24/7', 'Площадка из экоматериалов', 'BBQ и качели'],
    townhouseTop: 'Fold-out · Private collection', townhouseTitle: 'Шесть частных резиденций.', townhouseText: 'Официальная концепция двухэтажного блока всего на 6 таунхаусов площадью до 150 м², с террасой первого этажа.', townhouseFacts: ['2 этажа', '6 лотов в концепции', 'до 150 м²', 'терраса первого этажа'], townhouseWarning: 'Концепция не подтверждает, что таунхаусы построены или доступны в продаже. Актуальный статус уточняет отдел продаж.', expand: 'Раскрыть концепт', collapse: 'Свернуть концепт',
    hallsTop: 'Plate 04 · Зимний сад', hallsTitle: 'Холл продолжает ландшафт.', hallsText: 'Безбарьерный вход на уровне земли, колясочные, зоны ожидания и живые растения формируют спокойное ежедневное пространство.', hallCaptions: ['Холл с живыми растениями', 'Зона ожидания', 'Интерьер входной группы', 'Безбарьерный вход', 'Материалы холла'], hallFacts: ['Вход без ступеней', 'Колясочные', 'Зоны ожидания', 'Живые растения'],
    functionTop: 'Field note · 05', functionTitle: 'Функция остаётся частью архитектуры.', functionText: 'Подземный и наземный паркинг, кладовые около 3 м², места для велосипедов и заявленное оборудование для зарядки электромобилей. Реальной фотографией подтверждаем только паркинг; остальные пункты остаются текстом официальной спецификации.', functionItems: [['Паркинг', 'Подземный и наземный'], ['Boxroom', 'Кладовые около 3 м²'], ['Велосипеды', 'Специальные места хранения'], ['Электромобили', 'Заявлено зарядное оборудование'], ['Безопасность', 'Закрытый двор и видеонаблюдение 24/7']], parkingCaption: 'Паркинг Botanika Saroyi · реальная фотография', schemeCaption: 'Схема двора · официальный рендерный материал', schemeText: 'Схемный вид помогает прочитать расположение двора и наружного паркинга. Он не является аэрофотографией готовой территории.',
    locationTop: 'Coordinates · 41.349876 / 69.330564', locationTitle: 'Рядом с Ботаническим садом.', locationText: 'Botanika Saroyi находится в Мирзо-Улугбекском районе, рядом с Ботаническим садом. В опубликованных материалах улица и номер различаются, поэтому перед визитом уточните точку.', map: 'Открыть координаты на карте', panorama: 'Открыть панораму 360', locationWarning: 'Близость к саду не означает отдельный вход на его территорию.', compositeCaption: 'Официальный аэрокомпозит · не текущая аэрофотография',
    catalogTop: 'Index of residences · 224/224', catalogTitle: 'Полный локальный snapshot квартир.', catalogText: '224 официальных предложения/планировки на 30 августа 2026 года: 77 однокомнатных, 111 двухкомнатных и 36 трёхкомнатных. Все основные планировки сохранены локально.', catalogFacts: [['36,95–82,25 м²', 'актуальные квартиры snapshot'], ['1–16', 'этажи'], ['2', 'подъезда'], ['604,3 млн–1,47 млрд UZS', 'текущая цена по акции']], catalogNote: '223 строки имеют isSale=true; одна строка включена официальным интерфейсом в итог 224 и находится в бронировании. Мы не называем весь набор свободным.', openCatalog: 'Открыть индекс резиденций',
    buildTop: 'Archive · 17 reports / 104 photographs', buildTitle: 'Стройка — отдельный датированный слой.', buildText: 'Репрезентативная выборка из официального архива: от июня 2024 до июля 2026. Эти кадры не смешиваются с актуальной фотогалереей и не являются live-потоком.', months: ['Июль 2026', 'Декабрь 2025', 'Июнь 2024'],
    contactTop: 'Consultation · 07', contactTitle: 'Продолжить исследование с конкретной квартирой.', contactText: 'Оставьте контакты — менеджер NRG-BI подтвердит актуальные условия, срок и статус выбранного предложения.', privacy: 'Обработка персональных данных', phone: 'Телефон', top: 'Наверх', disclaimer: 'Материалы и snapshot не являются публичной офертой. Актуальные условия подтверждает отдел продаж.',
    kind: { photo: 'Реальная фотография', render: 'Официальный рендер', scheme: 'Официальная схема / рендер', composite: 'Официальный композит', archive: 'Архив стройки' }, previous: 'Предыдущий материал', next: 'Следующий материал', openImage: 'Открыть изображение', closeImage: 'Закрыть изображение', gallery: 'Фотогалерея', formTagline: 'Живой атлас дома.', formFacts: ['Бизнес-класс', '16 этажей', '45%+ озеленения'],
  },
  uz: {
    skip: 'Mazmunga o‘tish', menu: 'Navigatsiyani ochish', closeMenu: 'Navigatsiyani yopish', navigation: 'Navigatsiya', language: 'Til',
    nav: ['Dala qaydlari', 'Arxitektura', 'Jonli kolleksiya', 'Hovli', 'Xollar', 'Joylashuv'], catalogue: 'Rezidensiyalar indeksi', consult: 'Maslahat olish',
    eyebrow: 'BOTANIKA SAROYI · BIZNES-KLASS · TOSHKENT', heroTitle: 'Uyning jonli', heroAccent: 'atlasi.', heroText: 'Arxitektura, hovli va yetuk ko‘kalamzor — loyihaning bajarilgan qismlaridan olingan haqiqiy suratlarda.', heroLabel: 'Plate 01 · Haqiqiy surat', heroAlt: 'Botanika Saroyi loyihasining bajarilgan qismi fasadlarining haqiqiy surati', heroNote: 'Mirzo Ulug‘bek tumani · Botanika bog‘i yonida',
    manifestTop: 'Field note · 00', manifestTitle: 'Uy va’dalar bilan emas, faktlar bilan o‘qiladi.', manifestText: 'Botanika Saroyi — Botanika bog‘i yonidagi biznes-klass majmua. Haqiqiy suratlar, rasmiy konseptlar va qurilish arxivi alohida ko‘rsatiladi.',
    facts: [['Biznes', 'rasmiy klass'], ['16', 'qavat'], ['3 m dan', 'shift balandligi'], ['45%+', 'hudud — ko‘kalamzor'], ['2026-yil IV chorak', 'eng yaqin topshirish']],
    architectureTop: 'Plate 02 · Arxitektura', architectureTitle: 'Limestone, metall va sharqona ritm.', architectureText: 'Haqiqiy fasadlar rasmiy vizualizatsiyadan alohida. Naqsh arxitekturaning ichki ritmidir.', facadeCaptions: ['Fasad va tabiiy tosh', 'Hovli tomondan arxitektura', 'Loyihaning bajarilgan qismi fasadi'], renderTitle: 'Arxitektura konsepsiyasi', renderText: 'Rasmiy render materiallar va kompozitsiya g‘oyasini ko‘rsatadi. Bu joriy holat surati emas.',
    materialsTop: 'Material ledger · 01–05', materialsTitle: 'Materiallar xarakter konstruksiyasiga aylanadi.', materials: [['Karkas', 'Monolit temir-beton'], ['Xonadonlararo devorlar', '250 mm keramik terim'], ['Tosh', 'Tabiiy limestone'], ['Fasad', 'Alyuminiy kompozit panellar'], ['Oynalar', 'Uch kamerali profil · ko‘p funksiyali shisha paket']],
    botanyTop: 'Specimen index · 45%+', botanyTitle: 'Fon ko‘kalamzori emas, jonli kolleksiya.', botanyText: 'Suratlarda haqiqiy landshaft, indeksda esa e’lon qilingan ekin tarkibi ko‘rsatiladi.', plants: [['Daraxtlar', 'olxo‘ri · qarag‘ay · tikanli archa · liriodendron · chetan · zarang · jo‘ka · katalpa · qora va tog‘ qarag‘ayi'], ['Ignabarglilar', 'kiparis · tuya · mojjevelnik · shamshod'], ['Butalar', 'zirk · beresklet · nandina · ligustrum · puzyreplodnik · veygela · kalina · lavrovishnya · siren · kizilnik · fotiniya · spireya'], ['Gullaydiganlar', 'lavanda · geran · atirgul · gortenziya · liliynik · sedum'], ['O‘tlar', 'pennisetum']], landscapePhoto: 'Loyiha ko‘kalamzorining haqiqiy surati',
    courtyardTop: 'Plate 03 · Hovli allaqachon mavjud', courtyardTitle: 'Avtomobilsiz. Ko‘kalamzorli. Kunning turli ritmlari uchun.', courtyardText: 'Yopiq hudud, 24/7 videokuzatuv, ekologik materiallardan bolalar maydonchasi, BBQ, arg‘imchoqlar va sokin zonalar loyiha materiallarida ko‘rsatilgan. Bu yerda faqat haqiqiy fototurkum.', courtyardCaptions: ['Mavjud ko‘kalamzor hovli', 'Maydoncha va dam olish zonalari', 'Avtomobilsiz hovli', 'Ko‘kalamzor ichidagi sokin zona'], courtyardFacts: ['Yopiq hudud', '24/7 videokuzatuv', 'Ekomaterialli maydoncha', 'BBQ va arg‘imchoqlar'],
    townhouseTop: 'Fold-out · Private collection', townhouseTitle: 'Olti xususiy rezidensiya.', townhouseText: 'Faqat 6 ta, 150 m² gacha bo‘lgan va birinchi qavat terassasiga ega ikki qavatli taunhaus bloki bo‘yicha rasmiy konsepsiya.', townhouseFacts: ['2 qavat', 'Konsepsiyada 6 ta lot', '150 m² gacha', 'Birinchi qavat terassasi'], townhouseWarning: 'Konsepsiya taunhauslar qurilgani yoki sotuvda mavjudligini tasdiqlamaydi. Joriy holatni sotuv bo‘limidan aniqlang.', expand: 'Konseptni ochish', collapse: 'Konseptni yopish',
    hallsTop: 'Plate 04 · Qishki bog‘', hallsTitle: 'Xoll landshaftni davom ettiradi.', hallsText: 'Yer sathidagi to‘siqsiz kirish, aravachalar xonasi, kutish zonalari va jonli o‘simliklar sokin makonni yaratadi.', hallCaptions: ['Jonli o‘simlikli xoll', 'Kutish zonasi', 'Kirish guruhi interyeri', 'To‘siqsiz kirish', 'Xoll materiallari'], hallFacts: ['Zinasiz kirish', 'Aravachalar xonasi', 'Kutish zonalari', 'Jonli o‘simliklar'],
    functionTop: 'Field note · 05', functionTitle: 'Funksiya arxitekturaning bir qismi bo‘lib qoladi.', functionText: 'Yerosti va yerusti parking, taxminan 3 m² boxroom, velosiped saqlash joylari va e’lon qilingan elektromobil quvvatlash uskunasi. Haqiqiy surat bilan faqat parking tasdiqlanadi.', functionItems: [['Parking', 'Yerosti va yerusti'], ['Boxroom', 'Taxminan 3 m² ombor'], ['Velosipedlar', 'Maxsus saqlash joylari'], ['Elektromobillar', 'Quvvatlash uskunasi e’lon qilingan'], ['Xavfsizlik', 'Yopiq hovli va 24/7 videokuzatuv']], parkingCaption: 'Botanika Saroyi parkingi · haqiqiy surat', schemeCaption: 'Hovli sxemasi · rasmiy render materiali', schemeText: 'Sxema hovli va tashqi parking joylashuvini ko‘rsatadi. Bu tayyor hududning aerosurati emas.',
    locationTop: 'Coordinates · 41.349876 / 69.330564', locationTitle: 'Botanika bog‘i yonida.', locationText: 'Botanika Saroyi Mirzo Ulug‘bek tumanida, Botanika bog‘i yonida joylashgan. E’lon qilingan materiallarda ko‘cha va raqam turlicha ko‘rsatilgani uchun tashrifdan oldin aniq nuqtani tekshiring.', map: 'Koordinatalarni xaritada ochish', panorama: '360 panoramani ochish', locationWarning: 'Bog‘ga yaqinlik uning hududiga alohida kirish borligini anglatmaydi.', compositeCaption: 'Rasmiy aerokompozit · joriy aerosurat emas',
    catalogTop: 'Index of residences · 224/224', catalogTitle: 'Xonadonlarning to‘liq mahalliy snapshoti.', catalogText: '2026-yil 30-avgustdagi 224 rasmiy taklif/reja: 77 ta bir xonali, 111 ta ikki xonali va 36 ta uch xonali. Barcha asosiy rejalar mahalliy saqlangan.', catalogFacts: [['36,95–82,25 m²', 'snapshotdagi joriy xonadonlar'], ['1–16', 'qavatlar'], ['2', 'kirish'], ['604,3 mln–1,47 mlrd UZS', 'aksiya bo‘yicha joriy narx']], catalogNote: '223 qatorda isSale=true; bitta bron holatidagi qator rasmiy interfeysning 224 natijasiga kiradi. Butun to‘plamni bo‘sh deb atamaymiz.', openCatalog: 'Rezidensiyalar indeksini ochish',
    buildTop: 'Archive · 17 reports / 104 photographs', buildTitle: 'Qurilish — alohida sanalangan qatlam.', buildText: 'Rasmiy arxivdan 2024-yil iyundan 2026-yil iyulgacha bo‘lgan vakillik tanlovi. Bu kadrlar joriy galereyaga qo‘shilmaydi va live oqim emas.', months: ['2026-yil iyul', '2025-yil dekabr', '2024-yil iyun'],
    contactTop: 'Consultation · 07', contactTitle: 'Tadqiqotni aniq xonadon bilan davom ettiring.', contactText: 'Kontakt qoldiring — NRG-BI menejeri tanlangan taklifning joriy shartlari, muddati va holatini tasdiqlaydi.', privacy: 'Shaxsiy ma’lumotlarni qayta ishlash', phone: 'Telefon', top: 'Yuqoriga', disclaimer: 'Materiallar va snapshot ommaviy oferta emas. Joriy shartlarni sotuv bo‘limi tasdiqlaydi.',
    kind: { photo: 'Haqiqiy surat', render: 'Rasmiy render', scheme: 'Rasmiy sxema / render', composite: 'Rasmiy kompozit', archive: 'Qurilish arxivi' }, previous: 'Oldingi material', next: 'Keyingi material', openImage: 'Tasvirni ochish', closeImage: 'Tasvirni yopish', gallery: 'Fotogalereya', formTagline: 'Uyning jonli atlasi.', formFacts: ['Biznes-klass', '16 qavat', '45%+ ko‘kalamzor'],
  },
  en: {
    skip: 'Skip to content', menu: 'Open navigation', closeMenu: 'Close navigation', navigation: 'Navigation', language: 'Language',
    nav: ['Field notes', 'Architecture', 'Living collection', 'Courtyard', 'Lobbies', 'Location'], catalogue: 'Residence index', consult: 'Request a consultation',
    eyebrow: 'BOTANIKA SAROYI · BUSINESS CLASS · TASHKENT', heroTitle: 'A living atlas', heroAccent: 'of home.', heroText: 'Architecture, courtyard and mature planting—shown through actual photographs of completed parts of the project.', heroLabel: 'Plate 01 · Actual photography', heroAlt: 'Actual photograph of façades in a completed part of Botanika Saroyi', heroNote: 'Mirzo Ulugbek district · by the Botanical Garden',
    manifestTop: 'Field note · 00', manifestTitle: 'A home is read through evidence, not promises.', manifestText: 'Botanika Saroyi is a business-class project by the Botanical Garden. Actual photography, official concepts and the construction archive remain separate.',
    facts: [['Business', 'official class'], ['16', 'storeys'], ['from 3 m', 'ceiling height'], ['45%+', 'of the grounds planted'], ['Q4 2026', 'nearest completion']],
    architectureTop: 'Plate 02 · Architecture', architectureTitle: 'Limestone, metal and an eastern rhythm.', architectureText: 'Actual façades are kept separate from the official visualization. Ornament works as an architectural rhythm.', facadeCaptions: ['Façade and natural stone', 'Courtyard-side architecture', 'Façade of a completed part of the project'], renderTitle: 'Architectural concept', renderText: 'The official render explains the material and compositional intent. It is not a photograph of the current state.',
    materialsTop: 'Material ledger · 01–05', materialsTitle: 'Materials construct the character.', materials: [['Frame', 'Monolithic reinforced concrete'], ['Party walls', '250 mm ceramic masonry'], ['Stone', 'Natural limestone'], ['Façade', 'Aluminium composite panels'], ['Glazing', 'Three-chamber profile · multifunctional glazing']],
    botanyTop: 'Specimen index · 45%+', botanyTitle: 'A living collection, not background greenery.', botanyText: 'Photography shows the real project landscape; the index records the declared planting palette.', plants: [['Trees', 'plum · pine · blue spruce · tulip tree · rowan · maple · linden · catalpa · black and mountain pine'], ['Conifers', 'cypress · thuja · juniper · boxwood'], ['Shrubs', 'barberry · euonymus · nandina · privet · ninebark · weigela · viburnum · cherry laurel · lilac · cotoneaster · photinia · spiraea'], ['Flowering', 'lavender · geranium · roses · hydrangeas · daylily · sedum'], ['Grasses', 'pennisetum']], landscapePhoto: 'Actual photograph of the project landscaping',
    courtyardTop: 'Plate 03 · The courtyard already exists', courtyardTitle: 'Car-free. Planted. Ready for different daily rhythms.', courtyardText: 'A closed perimeter, 24/7 CCTV, an eco-material play area, BBQ, swings and quiet zones are listed in the project materials. This chapter contains only actual photography.', courtyardCaptions: ['Existing landscaped courtyard', 'Play and rest areas', 'Car-free courtyard', 'Quiet zone among planting'], courtyardFacts: ['Closed perimeter', '24/7 CCTV', 'Eco-material play area', 'BBQ and swings'],
    townhouseTop: 'Fold-out · Private collection', townhouseTitle: 'Six private residences.', townhouseText: 'An official concept for a two-storey block of six townhouses up to 150 m², with a ground-floor terrace.', townhouseFacts: ['2 storeys', '6 lots in the concept', 'up to 150 m²', 'ground-floor terrace'], townhouseWarning: 'The concept does not confirm that the townhouses are built or currently for sale. Ask the sales team for current availability.', expand: 'Unfold the concept', collapse: 'Fold the concept',
    hallsTop: 'Plate 04 · Winter garden', hallsTitle: 'The lobby continues the landscape.', hallsText: 'Step-free ground-level access, stroller rooms, waiting areas and live plants create a calm everyday interior.', hallCaptions: ['Lobby with live planting', 'Waiting area', 'Entrance interior', 'Barrier-free entrance', 'Lobby materials'], hallFacts: ['Step-free entrance', 'Stroller rooms', 'Waiting areas', 'Live plants'],
    functionTop: 'Field note · 05', functionTitle: 'Function remains part of the architecture.', functionText: 'Underground and surface parking, storage rooms of about 3 m², bicycle storage and declared EV charging equipment. Only the parking is confirmed with actual photography.', functionItems: [['Parking', 'Underground and surface'], ['Boxroom', 'Storage rooms of about 3 m²'], ['Bicycles', 'Dedicated storage'], ['Electric vehicles', 'Charging equipment is declared'], ['Security', 'Closed courtyard and 24/7 CCTV']], parkingCaption: 'Botanika Saroyi parking · actual photography', schemeCaption: 'Courtyard scheme · official rendered material', schemeText: 'The scheme explains the courtyard and surface-parking layout. It is not an aerial photograph of completed grounds.',
    locationTop: 'Coordinates · 41.349876 / 69.330564', locationTitle: 'By the Botanical Garden.', locationText: 'Botanika Saroyi is in Mirzo Ulugbek district, by the Botanical Garden. Published materials differ on the street and number, so confirm the precise point before visiting.', map: 'Open coordinates on the map', panorama: 'Open the 360 panorama', locationWarning: 'Proximity to the garden does not imply a private entrance into it.', compositeCaption: 'Official aerial composite · not current aerial photography',
    catalogTop: 'Index of residences · 224/224', catalogTitle: 'The complete local apartment snapshot.', catalogText: '224 official listings/layouts captured on 30 August 2026: 77 one-room, 111 two-room and 36 three-room apartments. Every primary floorplan is stored locally.', catalogFacts: [['36.95–82.25 m²', 'current snapshot apartments'], ['1–16', 'floors'], ['2', 'entrances'], ['UZS 604.3m–1.47bn', 'current campaign price']], catalogNote: '223 rows have isSale=true; one booking row is included in the official total of 224. We do not call the whole set available.', openCatalog: 'Open the residence index',
    buildTop: 'Archive · 17 reports / 104 photographs', buildTitle: 'Construction is a separate, dated layer.', buildText: 'A representative official-archive selection spanning June 2024 to July 2026. These frames never mix with current photography and are not a live feed.', months: ['July 2026', 'December 2025', 'June 2024'],
    contactTop: 'Consultation · 07', contactTitle: 'Continue the study with a specific apartment.', contactText: 'Leave your details and an NRG-BI manager will confirm the current terms, completion date and status of the selected listing.', privacy: 'Personal data processing', phone: 'Phone', top: 'Back to top', disclaimer: 'Materials and the snapshot are not a public offer. Current terms are confirmed by the sales team.',
    kind: { photo: 'Actual photography', render: 'Official render', scheme: 'Official scheme / render', composite: 'Official composite', archive: 'Construction archive' }, previous: 'Previous material', next: 'Next material', openImage: 'Open image', closeImage: 'Close image', gallery: 'Photo gallery', formTagline: 'A living atlas of home.', formFacts: ['Business class', '16 storeys', '45%+ planted'],
  },
} as const;

const facadeSlides: Slide[] = ['/facade-02.webp', '/facade-03.webp', '/facade-04.webp'].map((name) => ({ src: `/botanika-saroyi/images${name}`, kind: 'photo' }));
const courtyardSlides: Slide[] = ['/courtyard-01.webp', '/courtyard-02.webp', '/courtyard-03.webp', '/courtyard-04.webp'].map((name) => ({ src: `/botanika-saroyi/images${name}`, kind: 'photo' }));
const hallSlides: Slide[] = ['/hall-01.webp', '/hall-02.webp', '/hall-03.webp', '/hall-04.webp', '/hall-05.webp'].map((name) => ({ src: `/botanika-saroyi/images${name}`, kind: 'photo' }));
const buildSlides: Slide[] = ['/construction-2026-07.webp', '/construction-2025-12.webp', '/construction-2024-06.webp'].map((name) => ({ src: `/botanika-saroyi/images${name}`, kind: 'archive' }));
const greenery = [1, 2, 3, 4, 5].map((number) => `/botanika-saroyi/images/greenery-0${number}.webp`);
const anchorIds = ['botanika-project', 'botanika-architecture', 'botanika-botany', 'botanika-courtyard', 'botanika-halls', 'botanika-location'];

function asset(path: string) { return `${appBasePath}${path}`; }
function withLanguage(path: string, language: Language) { return `${appBasePath}${path}?lang=${language}`; }
function privacyUrl(language: Language) { return `${withLanguage('/privacy', language)}&project=botanika-saroyi`; }
function scrollBehavior(): ScrollBehavior { return window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth'; }

function Lightbox({ id, slides, captions, index, language, onMove, onClose }: { id: string; slides: Slide[]; captions: readonly string[]; index: number; language: Language; onMove: (direction: number) => void; onClose: () => void }) {
  const panelRef = useRef<HTMLDivElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);
  const touchStart = useRef<number | undefined>(undefined);
  const t = copy[language];
  useEffect(() => {
    const opener = document.activeElement as HTMLElement | null;
    document.body.classList.add('botanika-overlay-locked'); closeRef.current?.focus();
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { event.preventDefault(); onClose(); return; }
      if (event.key === 'ArrowLeft') { event.preventDefault(); onMove(-1); return; }
      if (event.key === 'ArrowRight') { event.preventDefault(); onMove(1); return; }
      if (event.key !== 'Tab' || !panelRef.current) return;
      const focusable = Array.from(panelRef.current.querySelectorAll<HTMLElement>('button:not([disabled])'));
      const first = focusable[0]; const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    window.addEventListener('keydown', onKey);
    return () => { document.body.classList.remove('botanika-overlay-locked'); window.removeEventListener('keydown', onKey); window.requestAnimationFrame(() => opener?.isConnected && opener.focus()); };
  }, [onClose, onMove]);
  const slide = slides[index];
  return <div className="botanika-lightbox" role="dialog" aria-modal="true" aria-labelledby={`${id}-caption`} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><div ref={panelRef} className="botanika-lightbox__panel" onTouchStart={(event) => { event.stopPropagation(); touchStart.current = event.touches[0]?.clientX; }} onTouchEnd={(event) => { event.stopPropagation(); const distance = (event.changedTouches[0]?.clientX ?? 0) - (touchStart.current ?? 0); if (Math.abs(distance) > 44) onMove(distance > 0 ? -1 : 1); touchStart.current = undefined; }}><button ref={closeRef} className="botanika-lightbox__close" type="button" onClick={onClose} aria-label={t.closeImage}>×</button><img src={asset(slide.src)} alt={`${t.kind[slide.kind]} · ${captions[index]}`} /><footer id={`${id}-caption`} aria-live="polite"><span>{t.kind[slide.kind]}</span><strong>{captions[index]}</strong><small>{index + 1} / {slides.length}</small></footer><button className="botanika-lightbox__previous" type="button" onClick={() => onMove(-1)} aria-label={t.previous}>←</button><button className="botanika-lightbox__next" type="button" onClick={() => onMove(1)} aria-label={t.next}>→</button></div></div>;
}

function Gallery({ id, slides, captions, language }: { id: string; slides: Slide[]; captions: readonly string[]; language: Language }) {
  const [index, setIndex] = useState(0);
  const [lightbox, setLightbox] = useState(false);
  const touchStart = useRef<number | undefined>(undefined);
  const t = copy[language];
  const move = useCallback((direction: number) => setIndex((value) => (value + direction + slides.length) % slides.length), [slides.length]);
  const closeLightbox = useCallback(() => setLightbox(false), []);
  const onKey = (event: ReactKeyboardEvent<HTMLDivElement>) => { if ((event.target as HTMLElement).closest('.botanika-lightbox')) return; if (event.key === 'ArrowLeft') { event.preventDefault(); move(-1); } if (event.key === 'ArrowRight') { event.preventDefault(); move(1); } if (event.key === 'Home') { event.preventDefault(); setIndex(0); } if (event.key === 'End') { event.preventDefault(); setIndex(slides.length - 1); } };
  const onTouchStart = (event: ReactTouchEvent) => { touchStart.current = event.touches[0]?.clientX; };
  const onTouchEnd = (event: ReactTouchEvent) => { const distance = (event.changedTouches[0]?.clientX ?? 0) - (touchStart.current ?? 0); if (Math.abs(distance) > 44) move(distance > 0 ? -1 : 1); touchStart.current = undefined; };
  const slide = slides[index];
  return <div className="botanika-gallery" role="region" tabIndex={0} onKeyDown={onKey} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd} aria-roledescription={t.gallery} aria-label={captions[index]}><button className="botanika-gallery__image" type="button" onClick={() => setLightbox(true)} aria-label={`${t.openImage}: ${captions[index]}`}><img key={slide.src} src={asset(slide.src)} alt={`${t.kind[slide.kind]} · ${captions[index]}`} loading="lazy" decoding="async" /></button><div className="botanika-gallery__meta" aria-live="polite"><span>{t.kind[slide.kind]}</span><strong>{captions[index]}</strong><small>{String(index + 1).padStart(2, '0')} / {String(slides.length).padStart(2, '0')}</small></div><div className="botanika-gallery__controls"><button type="button" onClick={() => move(-1)} aria-label={t.previous}>←</button><button type="button" onClick={() => move(1)} aria-label={t.next}>→</button></div>{lightbox ? <Lightbox id={id} slides={slides} captions={captions} index={index} language={language} onMove={move} onClose={closeLightbox} /> : null}</div>;
}

export function BotanikaSaroyiPage({ initialLanguage }: { initialLanguage: Language }) {
  const router = useRouter();
  const language = initialLanguage;
  const [menuOpen, setMenuOpen] = useState(false);
  const [headerScrolled, setHeaderScrolled] = useState(false);
  const [plantIndex, setPlantIndex] = useState(0);
  const [townhouseOpen, setTownhouseOpen] = useState(false);
  const [leadContext, setLeadContext] = useState<string>();
  const menuRef = useRef<HTMLElement>(null);
  const menuCloseRef = useRef<HTMLButtonElement>(null);
  const menuTriggerRef = useRef<HTMLButtonElement>(null);
  const menuRestoreFocusRef = useRef(true);
  const t = copy[language];

  useEffect(() => {
    const url = new URL(window.location.href);
    if (!url.searchParams.has('lang')) {
      const stored = window.localStorage.getItem('botanika-saroyi-language');
      const fallback = stored === 'uz' || stored === 'en' || stored === 'ru' ? stored : language;
      url.searchParams.set('lang', fallback);
      router.replace(`${url.pathname}?${url.searchParams.toString()}${url.hash}`, { scroll: false });
      if (fallback !== language) return;
    }
    document.documentElement.lang = language;
    document.documentElement.classList.add('botanika-scroll-smooth');
    window.localStorage.setItem('botanika-saroyi-language', language);
    return () => document.documentElement.classList.remove('botanika-scroll-smooth');
  }, [language, router]);
  useEffect(() => { const update = () => setHeaderScrolled(window.scrollY > 40); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  useEffect(() => { const elements = Array.from(document.querySelectorAll<HTMLElement>('[data-botanika-reveal]')); if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { elements.forEach((element) => element.classList.add('is-visible')); return; } const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .12, rootMargin: '0px 0px -8% 0px' }); elements.forEach((element) => observer.observe(element)); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!menuOpen) return; const trigger = menuTriggerRef.current; document.body.classList.add('botanika-overlay-locked'); menuCloseRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); setMenuOpen(false); return; } if (event.key !== 'Tab' || !menuRef.current) return; const focusable = Array.from(menuRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; window.addEventListener('keydown', onKey); return () => { const restoreFocus = menuRestoreFocusRef.current; menuRestoreFocusRef.current = true; document.body.classList.remove('botanika-overlay-locked'); window.removeEventListener('keydown', onKey); if (restoreFocus) window.requestAnimationFrame(() => trigger?.focus({ preventScroll: true })); }; }, [menuOpen]);

  const setLanguage = (next: Language) => { window.localStorage.setItem('botanika-saroyi-language', next); const url = new URL(window.location.href); url.searchParams.set('lang', next); router.replace(`${url.pathname}?${url.searchParams.toString()}${url.hash}`, { scroll: false }); };
  const goToAnchor = (event: ReactMouseEvent<HTMLAnchorElement>, id: string) => { event.preventDefault(); if (menuOpen) menuRestoreFocusRef.current = false; setMenuOpen(false); window.requestAnimationFrame(() => { const section = document.getElementById(id); section?.scrollIntoView({ behavior: scrollBehavior(), block: 'start' }); section?.focus({ preventScroll: true }); const url = new URL(window.location.href); url.hash = id; window.history.replaceState({}, '', url); }); };
  const openLead = (surface: string) => setLeadContext(`botanika-saroyi:landing:${surface}:lang=${language}`);

  return <main className="botanika-site" lang={language}>
    <a className="botanika-skip" href="#botanika-content">{t.skip}</a>
    <header className={`botanika-header ${headerScrolled ? 'is-scrolled' : ''}`} aria-label={t.navigation}><a className="botanika-wordmark" href={withLanguage('/botanika-saroyi', language)} aria-label="Botanika Saroyi">BOTANIKA <span>SAROYI</span></a><nav>{t.nav.slice(0, 4).map((label, index) => <a key={label} href={`#${anchorIds[index]}`} onClick={(event) => goToAnchor(event, anchorIds[index])}>{label}</a>)}</nav><div className="botanika-header__actions"><a className="botanika-header__catalog" href={withLanguage('/botanika-saroyi/apartments', language)}>{t.catalogue}</a><div className="botanika-languages" role="group" aria-label={t.language}>{languages.map((item) => <button type="button" key={item} className={language === item ? 'is-active' : ''} aria-pressed={language === item} onClick={() => setLanguage(item)}>{item.toUpperCase()}</button>)}</div><button ref={menuTriggerRef} className="botanika-menu-trigger" type="button" aria-expanded={menuOpen} aria-controls="botanika-mobile-menu" onClick={() => { menuRestoreFocusRef.current = true; setMenuOpen(true); }}>{t.menu}</button></div></header>
    {menuOpen ? <nav id="botanika-mobile-menu" ref={menuRef} className="botanika-menu" role="dialog" aria-modal="true" aria-label={t.navigation}><header><span>BOTANIKA SAROYI</span><button ref={menuCloseRef} type="button" onClick={() => setMenuOpen(false)} aria-label={t.closeMenu}>×</button></header><div>{t.nav.map((label, index) => <a key={label} href={`#${anchorIds[index]}`} onClick={(event) => goToAnchor(event, anchorIds[index])}><small>{String(index + 1).padStart(2, '0')}</small>{label}</a>)}</div><a className="botanika-menu__catalog" href={withLanguage('/botanika-saroyi/apartments', language)}>{t.catalogue}<span aria-hidden="true">↗</span></a></nav> : null}

    <section className="botanika-hero" id="botanika-content" tabIndex={-1}><div className="botanika-hero__image"><img src={asset('/botanika-saroyi/images/hero.webp')} alt={t.heroAlt} fetchPriority="high" /><span>{t.heroLabel}</span></div><div className="botanika-hero__copy"><p>{t.eyebrow}</p><h1>{t.heroTitle}<em>{t.heroAccent}</em></h1><div><span>{t.heroText}</span><small>{t.heroNote}</small></div><div className="botanika-hero__actions"><a href={withLanguage('/botanika-saroyi/apartments', language)}>{t.catalogue}<b aria-hidden="true">↗</b></a><button type="button" data-lead-trigger onClick={() => openLead('hero-consultation')}>{t.consult}</button></div></div><aside aria-hidden="true"><span>01</span><small>FIELD NOTES<br />41.349876 N<br />69.330564 E</small></aside></section>

    <section className="botanika-manifest" id="botanika-project" tabIndex={-1} data-botanika-reveal><header><small>{t.manifestTop}</small><h2>{t.manifestTitle}</h2><p>{t.manifestText}</p></header><div className="botanika-facts">{t.facts.map(([value, label], index) => <article key={label}><small>{String(index + 1).padStart(2, '0')}</small><strong>{value}</strong><span>{label}</span></article>)}</div></section>

    <section className="botanika-architecture" id="botanika-architecture" tabIndex={-1}><header data-botanika-reveal><small>{t.architectureTop}</small><h2>{t.architectureTitle}</h2><p>{t.architectureText}</p></header><div className="botanika-architecture__spread"><Gallery id="facades" slides={facadeSlides} captions={t.facadeCaptions} language={language} /><figure data-botanika-reveal><div><img src={asset('/botanika-saroyi/images/architecture-concept.webp')} alt={`${t.kind.render} · ${t.renderTitle}`} loading="lazy" /><span>{t.kind.render}</span></div><figcaption><small>Plate 02B</small><h3>{t.renderTitle}</h3><p>{t.renderText}</p></figcaption></figure></div><div className="botanika-materials" data-botanika-reveal><header><small>{t.materialsTop}</small><h3>{t.materialsTitle}</h3></header><dl>{t.materials.map(([label, value], index) => <div key={label}><span>{String(index + 1).padStart(2, '0')}</span><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></section>

    <section className="botanika-botany" id="botanika-botany" tabIndex={-1}><header data-botanika-reveal><small>{t.botanyTop}</small><h2>{t.botanyTitle}</h2><p>{t.botanyText}</p></header><div className="botanika-botany__index"><div role="tablist" aria-label={t.botanyTitle}>{t.plants.map(([label], index) => <button id={`botanika-plant-tab-${index}`} type="button" role="tab" aria-selected={plantIndex === index} aria-controls={`botanika-plant-panel-${index}`} tabIndex={plantIndex === index ? 0 : -1} className={plantIndex === index ? 'is-active' : ''} key={label} onClick={() => setPlantIndex(index)} onKeyDown={(event) => { const next = event.key === 'ArrowRight' || event.key === 'ArrowDown' ? (index + 1) % t.plants.length : event.key === 'ArrowLeft' || event.key === 'ArrowUp' ? (index - 1 + t.plants.length) % t.plants.length : event.key === 'Home' ? 0 : event.key === 'End' ? t.plants.length - 1 : -1; if (next >= 0) { event.preventDefault(); setPlantIndex(next); window.requestAnimationFrame(() => document.getElementById(`botanika-plant-tab-${next}`)?.focus()); } }}><small>{String(index + 1).padStart(2, '0')}</small><span>{label}</span></button>)}</div><article id={`botanika-plant-panel-${plantIndex}`} role="tabpanel" aria-labelledby={`botanika-plant-tab-${plantIndex}`}><p>{t.plants[plantIndex][1]}</p><figure><img key={greenery[plantIndex]} src={asset(greenery[plantIndex])} alt={t.landscapePhoto} loading="lazy" /><figcaption>{t.kind.photo} · {t.landscapePhoto}</figcaption></figure></article></div></section>

    <section className="botanika-courtyard" id="botanika-courtyard" tabIndex={-1}><header data-botanika-reveal><small>{t.courtyardTop}</small><h2>{t.courtyardTitle}</h2><p>{t.courtyardText}</p></header><div className="botanika-courtyard__body"><Gallery id="courtyard" slides={courtyardSlides} captions={t.courtyardCaptions} language={language} /><ul>{t.courtyardFacts.map((fact, index) => <li key={fact}><span>{String(index + 1).padStart(2, '0')}</span>{fact}</li>)}</ul></div></section>

    <section className={`botanika-townhouses ${townhouseOpen ? 'is-open' : ''}`}><div className="botanika-townhouses__cover"><small>{t.townhouseTop}</small><h2>{t.townhouseTitle}</h2><p>{t.townhouseText}</p><button type="button" aria-expanded={townhouseOpen} aria-controls="botanika-townhouse-fold" onClick={() => setTownhouseOpen((value) => !value)}>{townhouseOpen ? t.collapse : t.expand}<span aria-hidden="true">{townhouseOpen ? '−' : '+'}</span></button></div><div className="botanika-townhouses__fold" id="botanika-townhouse-fold" aria-hidden={!townhouseOpen}><figure><img src={asset('/botanika-saroyi/images/townhouse-concept.webp')} alt={`${t.kind.render} · ${t.townhouseTitle}`} loading="lazy" /><figcaption>{t.kind.render}</figcaption></figure><aside><dl>{t.townhouseFacts.map((fact, index) => <div key={fact}><dt>{String(index + 1).padStart(2, '0')}</dt><dd>{fact}</dd></div>)}</dl><p>{t.townhouseWarning}</p></aside></div></section>

    <section className="botanika-halls" id="botanika-halls" tabIndex={-1}><header data-botanika-reveal><small>{t.hallsTop}</small><h2>{t.hallsTitle}</h2><p>{t.hallsText}</p></header><div className="botanika-halls__spread"><ul>{t.hallFacts.map((fact, index) => <li key={fact}><span>{String(index + 1).padStart(2, '0')}</span>{fact}</li>)}</ul><Gallery id="halls" slides={hallSlides} captions={t.hallCaptions} language={language} /></div></section>

    <section className="botanika-function"><header data-botanika-reveal><small>{t.functionTop}</small><h2>{t.functionTitle}</h2><p>{t.functionText}</p></header><div className="botanika-function__grid"><figure><img src={asset('/botanika-saroyi/images/parking.webp')} alt={t.parkingCaption} loading="lazy" /><figcaption>{t.kind.photo} · {t.parkingCaption}</figcaption></figure><dl>{t.functionItems.map(([label, value], index) => <div key={label}><span>{String(index + 1).padStart(2, '0')}</span><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className="botanika-scheme"><figure><img src={asset('/botanika-saroyi/images/courtyard-scheme.webp')} alt={t.schemeCaption} loading="lazy" /><figcaption>{t.kind.scheme}</figcaption></figure><aside><small>Plate 05B</small><h3>{t.schemeCaption}</h3><p>{t.schemeText}</p></aside></div></section>

    <section className="botanika-location" id="botanika-location" tabIndex={-1}><figure><img src={asset('/botanika-saroyi/images/aerial-composite.webp')} alt={t.compositeCaption} loading="lazy" /><figcaption>{t.kind.composite} · {t.compositeCaption}</figcaption></figure><div data-botanika-reveal><small>{t.locationTop}</small><h2>{t.locationTitle}</h2><p>{t.locationText}</p><em>{t.locationWarning}</em><nav><a href={mapUrl} target="_blank" rel="noreferrer">{t.map}<span>↗</span></a><a href={panorama} target="_blank" rel="noreferrer">{t.panorama}<span>360°</span></a></nav></div></section>

    <section className="botanika-catalog-callout"><header data-botanika-reveal><small>{t.catalogTop}</small><h2>{t.catalogTitle}</h2><p>{t.catalogText}</p></header><div className="botanika-catalog-callout__facts">{t.catalogFacts.map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><div className="botanika-catalog-callout__actions"><p>{t.catalogNote}</p><a href={withLanguage('/botanika-saroyi/apartments', language)}>{t.openCatalog}<span>↗</span></a></div></section>

    <section className="botanika-build"><header data-botanika-reveal><small>{t.buildTop}</small><h2>{t.buildTitle}</h2><p>{t.buildText}</p></header><div className="botanika-build__grid">{buildSlides.map((slide, index) => <figure key={slide.src}><img src={asset(slide.src)} alt={`${t.kind.archive} · ${t.months[index]}`} loading="lazy" /><figcaption><span>{t.kind.archive}</span><strong>{t.months[index]}</strong><small>{String(index + 1).padStart(2, '0')}</small></figcaption></figure>)}</div><nav><a href={panorama} target="_blank" rel="noreferrer">{t.panorama}<span>360°</span></a></nav></section>

    <section className="botanika-contact"><small>{t.contactTop}</small><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div><button type="button" data-lead-trigger onClick={() => openLead('final-consultation')}>{t.consult}<span>↗</span></button><a href="tel:+998781137712"><small>{t.phone}</small><strong>+998 78 113 77 12</strong></a></div></section>
    <footer className="botanika-footer"><a className="botanika-wordmark" href={withLanguage('/botanika-saroyi', language)}>BOTANIKA <span>SAROYI</span></a><p>{t.disclaimer}</p><nav><a href={privacyUrl(language)}>{t.privacy}</a><a href="#botanika-content" onClick={(event) => goToAnchor(event, 'botanika-content')}>{t.top} ↑</a></nav></footer>
    {leadContext ? <div className="botanika-lead-host" data-project-slug="botanika-saroyi" data-context={leadContext}><LeadModal open language={language} context={leadContext} brandName="NRG-BI" projectName="BOTANIKA SAROYI" tagline={t.formTagline} facts={t.formFacts} submitUrl={botanikaLeadSubmitUrl()} projectSlug="botanika-saroyi" privacyUrl={privacyUrl(language)} requireConsent onClose={() => setLeadContext(undefined)} /></div> : null}
  </main>;
}
