'use client';

/* eslint-disable @next/next/no-img-element */

import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { type KeyboardEvent as ReactKeyboardEvent, type PointerEvent as ReactPointerEvent, useCallback, useEffect, useRef, useState } from 'react';
import { LeadModal } from '@/app/lead-modal';
import { useSaadiyatDocumentLanguage } from './saadiyat-language';
import { saadiyatLeadSubmitUrl } from './saadiyat-lead';

type Language = 'ru' | 'uz' | 'en';
type Unit = { id: string; crmId: string; number: string; rooms: number; area: number; floor: number; section: string; phase: string; completionYear: string; plan: string };
type Slide = { src: string; title: Record<Language, string>; text: Record<Language, string> };
type LightboxState = { index: number; opener: HTMLButtonElement };
const configuredBasePath = process.env.NEXT_PUBLIC_APP_BASE_PATH ?? '';
const basePath = configuredBasePath ? `/${configuredBasePath.replace(/^\/+|\/+$/g, '')}` : '';
const asset = (value: string) => `${basePath}${value}`;
const withLanguage = (value: string, language: Language) => `${basePath}${value}?lang=${language}`;
const languages: Language[] = ['ru', 'uz', 'en'];
const languageFrom = (value: string | null, fallback: Language): Language => value === 'ru' || value === 'uz' || value === 'en' ? value : fallback;

const gallery: Slide[] = [
  { src: '/saadiyat/images/water.webp', title: { ru: 'Водная гладь', uz: 'Suv yuzasi', en: 'Water surface' }, text: { ru: 'Тихий центр и главная архитектурная ось двора.', uz: 'Hovlining sokin markazi va asosiy me’moriy o‘qi.', en: 'A quiet centre and the courtyard’s main architectural axis.' } },
  { src: '/saadiyat/images/playground.webp', title: { ru: 'Открытые и закрытые площадки', uz: 'Ochiq va yopiq maydonchalar', en: 'Open and indoor playgrounds' }, text: { ru: 'Пространства для разных возрастов внутри безопасного двора.', uz: 'Xavfsiz hovlida turli yoshlar uchun makonlar.', en: 'Spaces for different ages within the protected courtyard.' } },
  { src: '/saadiyat/images/workout.webp', title: { ru: 'Workout под открытым небом', uz: 'Ochiq havodagi workout', en: 'Open-air workout' }, text: { ru: 'Спортивная зона в повседневном маршруте дома.', uz: 'Uyning kundalik yo‘nalishidagi sport hududi.', en: 'A fitness area on the everyday route through the grounds.' } },
  { src: '/saadiyat/images/teahouse.webp', title: { ru: 'Чайхана', uz: 'Choyxona', en: 'Teahouse' }, text: { ru: 'Место для неспешных встреч и восточного гостеприимства.', uz: 'Sokin uchrashuvlar va sharqona mehmondo‘stlik joyi.', en: 'A place for unhurried meetings and eastern hospitality.' } },
  { src: '/saadiyat/images/shadow-theatre.webp', title: { ru: 'Театр теней', uz: 'Soyalar teatri', en: 'Shadow theatre' }, text: { ru: 'Свет становится игрой, а тень — частью детства.', uz: 'Yorug‘lik o‘yinga, soya esa bolalikning bir qismiga aylanadi.', en: 'Light becomes play, and shadow becomes part of childhood.' } },
  { src: '/saadiyat/images/mist.webp', title: { ru: 'Адиабатическое распыление', uz: 'Adiabatik purkash', en: 'Adiabatic mist' }, text: { ru: 'Мягкий микроклимат и свежесть в жаркие дни.', uz: 'Issiq kunlarda yumshoq mikroiqlim va salqinlik.', en: 'A gentler microclimate and freshness on hot days.' } },
];

const copy = {
  ru: {
    leadFacts: ['Бизнес-класс', '14 блоков', 'IV квартал 2027'] as const,
    skip: 'К содержанию', menu: 'Меню', close: 'Закрыть', navLabel: 'Навигация Saadiyat', nav: [['idea', 'Идея'], ['architecture', 'Архитектура'], ['island', 'Двор'], ['lobby', 'Лобби'], ['location', 'Локация'], ['apartments', 'Квартиры']] as const,
    choose: 'Выбрать квартиру', consult: 'Получить консультацию', call: 'Позвонить', overline: 'ТАШКЕНТ · БИЗНЕС-КЛАСС · IV КВАРТАЛ 2027', heroTitle: 'Остров света.', heroText: 'Saadiyat — «Остров счастья»: приватный городской квартал, собранный вокруг тихой воды, света и ежедневных семейных ритуалов.', render: 'Официальная CGI-визуализация · проектный образ',
    stats: [['14', 'блоков'], ['710', 'квартир'], ['3', 'очереди'], ['20 500 м²', 'площадь проекта']] as const,
    ideaIndex: '01 · ИДЕЯ', ideaTitle: 'Счастье — не декорация. Это среда.', ideaText: 'Современная городская динамика здесь смягчается приватностью двора. Название Saadiyat переводится с арабского как «Остров счастья» — идея, вокруг которой построен весь маршрут проекта.',
    archIndex: '02 · АРХИТЕКТУРА', archTitle: 'Тёплый камень. Глубокая тень. Ритм арок.', archText: 'Архитектура создана международным бюро IND в сотрудничестве с ho.uz. Вентилируемые фасады соединяют клинкер и алюминиевые композитные панели в природной тёплой палитре.', facade: 'Фасад', entrance: 'Входная группа', materials: 'Материалы',
    islandIndex: '03 · ВНУТРИ ОСТРОВА', islandTitle: 'Двор, где вода становится воздухом.', islandText: 'Без машин, но с открытыми и закрытыми детскими площадками, workout, гостевой комнатой, чайханой, театром теней и водным распылением.', previous: 'Предыдущий кадр', next: 'Следующий кадр', openImage: 'Открыть кадр', closeImage: 'Закрыть галерею', imageOf: 'из',
    communityIndex: '04 · ОБЩИЕ ПРОСТРАНСТВА', communityTitle: 'Гостеприимство остаётся дома.', communityText: 'Гостевая комната и чайхана продолжают квартиру за её пределами. Подземный и наземный паркинг дополнены зарядками для электромобилей.', guest: 'Гостевая комната', parking: 'Паркинг и зарядки',
    lobbyIndex: '05 · ЛОББИ', lobbyTitle: 'Свет встречает первым.', lobbyText: 'Просторные лобби с витражными окнами, мягким освещением, лифтом к приватному двору и безбарьерным маршрутом.',
    locationIndex: '06 · ЛОКАЦИЯ', locationTitle: 'Между Катта Дархан и Аккурган.', locationText: 'Мирзо-Улугбекский район, Ташкент. Координаты объекта подтверждены официальной карточкой проекта.', coordinate: '41.332023° N · 69.307171° E',
    apartmentIndex: '07 · ЖИВОЙ КАТАЛОГ', apartmentTitle: 'Найдите свой ритм.', apartmentText: '159 доступных жилых позиций в свежем официальном snapshot. Цены скрыты источником и показываются только по запросу.', rooms: 'комн.', floor: 'этаж', phase: 'очередь', request: 'По запросу', viewAll: 'Открыть все квартиры', askUnit: 'Уточнить квартиру',
    contactIndex: '08 · КОНСУЛЬТАЦИЯ', contactTitle: 'Продолжим с конкретным сценарием.', contactText: 'Оставьте имя, телефон, цель покупки и согласие — менеджер TENCORP подготовит актуальную подборку.', privacy: 'Обработка персональных данных', disclaimer: 'Все изображения проекта — CGI/рендеры, если прямо не указано иное. Материалы и каталог не являются публичной офертой.', top: 'Наверх',
  },
  uz: {
    leadFacts: ['Biznes-klass', '14 ta blok', '2027-yil IV chorak'] as const,
    skip: 'Asosiy mazmunga', menu: 'Menyu', close: 'Yopish', navLabel: 'Saadiyat navigatsiyasi', nav: [['idea', 'G‘oya'], ['architecture', 'Arxitektura'], ['island', 'Hovli'], ['lobby', 'Lobbi'], ['location', 'Joylashuv'], ['apartments', 'Xonadonlar']] as const,
    choose: 'Xonadon tanlash', consult: 'Maslahat olish', call: 'Qo‘ng‘iroq', overline: 'TOSHKENT · BIZNES-KLASS · 2027-YIL IV CHORAK', heroTitle: 'Yorug‘lik oroli.', heroText: 'Saadiyat — «Baxt oroli»: sokin suv, yorug‘lik va oilaviy kundalik marosimlar atrofida qurilgan xususiy shahar kvartali.', render: 'Rasmiy CGI-vizualizatsiya · loyiha obrazi',
    stats: [['14', 'blok'], ['710', 'xonadon'], ['3', 'bosqich'], ['20 500 m²', 'loyiha maydoni']] as const,
    ideaIndex: '01 · G‘OYA', ideaTitle: 'Baxt bezak emas. Bu muhit.', ideaText: 'Zamonaviy shahar jo‘shqinligi hovli xususiyligi bilan yumshaydi. Saadiyat arab tilidan «Baxt oroli» deb tarjima qilinadi — loyiha yo‘nalishini birlashtiruvchi g‘oya.',
    archIndex: '02 · ARXITEKTURA', archTitle: 'Iliq tosh. Chuqur soya. Arkalar ritmi.', archText: 'Arxitektura IND xalqaro byurosi va ho.uz hamkorligida yaratilgan. Ventilyatsiyalanuvchi fasadlar klinker va alyuminiy kompozit panellarni iliq tabiiy palitrada birlashtiradi.', facade: 'Fasad', entrance: 'Kirish guruhi', materials: 'Materiallar',
    islandIndex: '03 · OROL ICHIDA', islandTitle: 'Suv havoga aylanadigan hovli.', islandText: 'Avtomobilsiz, ochiq va yopiq bolalar maydonchalari, workout, mehmon xonasi, choyxona, soyalar teatri va suv purkash tizimi bilan.', previous: 'Oldingi kadr', next: 'Keyingi kadr', openImage: 'Kadrni ochish', closeImage: 'Galereyani yopish', imageOf: 'dan',
    communityIndex: '04 · UMUMIY MAKONLAR', communityTitle: 'Mehmondo‘stlik uyda qoladi.', communityText: 'Mehmon xonasi va choyxona xonadonni uning tashqarisida davom ettiradi. Yerosti va yerusti parkinglari elektromobil quvvatlagichlari bilan jihozlanadi.', guest: 'Mehmon xonasi', parking: 'Parking va quvvatlash',
    lobbyIndex: '05 · LOBBI', lobbyTitle: 'Yorug‘lik birinchi bo‘lib kutib oladi.', lobbyText: 'Vitrajli derazalar, yumshoq yoritish, xususiy hovliga lift va to‘siqsiz yo‘nalishga ega keng lobbilar.',
    locationIndex: '06 · JOYLASHUV', locationTitle: 'Katta Darxon va Oqqo‘rg‘on oralig‘ida.', locationText: 'Mirzo Ulug‘bek tumani, Toshkent. Obyekt koordinatalari loyiha kartochkasida tasdiqlangan.', coordinate: '41.332023° N · 69.307171° E',
    apartmentIndex: '07 · JONLI KATALOG', apartmentTitle: 'O‘z ritmingizni toping.', apartmentText: 'Yangi rasmiy snapshotda 159 ta mavjud turar joy pozitsiyasi. Narx manbada yashirilgan va faqat so‘rov bo‘yicha beriladi.', rooms: 'xona', floor: 'qavat', phase: 'bosqich', request: 'So‘rov bo‘yicha', viewAll: 'Barcha xonadonlar', askUnit: 'Xonadonni aniqlash',
    contactIndex: '08 · MASLAHAT', contactTitle: 'Aniq ssenariy bilan davom etamiz.', contactText: 'Ism, telefon, xarid maqsadi va rozilikni qoldiring — TENCORP menejeri dolzarb variantlarni tayyorlaydi.', privacy: 'Shaxsiy ma’lumotlarni qayta ishlash', disclaimer: 'Loyihaning barcha tasvirlari, alohida aytilmagan bo‘lsa, CGI/renderdir. Materiallar va katalog ommaviy oferta emas.', top: 'Yuqoriga',
  },
  en: {
    leadFacts: ['Business class', '14 blocks', 'Q4 2027'] as const,
    skip: 'Skip to content', menu: 'Menu', close: 'Close', navLabel: 'Saadiyat navigation', nav: [['idea', 'Idea'], ['architecture', 'Architecture'], ['island', 'Courtyard'], ['lobby', 'Lobby'], ['location', 'Location'], ['apartments', 'Apartments']] as const,
    choose: 'Choose an apartment', consult: 'Request a consultation', call: 'Call', overline: 'TASHKENT · BUSINESS CLASS · Q4 2027', heroTitle: 'An island of light.', heroText: 'Saadiyat — the “Island of Happiness”: a private urban quarter composed around quiet water, light and everyday family rituals.', render: 'Official CGI visualisation · project concept',
    stats: [['14', 'blocks'], ['710', 'apartments'], ['3', 'phases'], ['20,500 m²', 'project area']] as const,
    ideaIndex: '01 · IDEA', ideaTitle: 'Happiness is not decoration. It is an environment.', ideaText: 'Modern urban energy is softened by the privacy of the courtyard. Saadiyat translates from Arabic as “Island of Happiness” — the idea that organises the entire project journey.',
    archIndex: '02 · ARCHITECTURE', archTitle: 'Warm stone. Deep shade. A rhythm of arches.', archText: 'The architecture was created by international bureau IND in collaboration with ho.uz. Ventilated facades pair clinker with aluminium composite panels in warm natural hues.', facade: 'Facade', entrance: 'Entrance group', materials: 'Materials',
    islandIndex: '03 · INSIDE THE ISLAND', islandTitle: 'A courtyard where water becomes air.', islandText: 'Car-free, with open and indoor playgrounds, workout, a guest room, teahouse, shadow theatre and water mist.', previous: 'Previous frame', next: 'Next frame', openImage: 'Open frame', closeImage: 'Close gallery', imageOf: 'of',
    communityIndex: '04 · SHARED SPACES', communityTitle: 'Hospitality stays close to home.', communityText: 'The guest room and teahouse extend the apartment beyond its walls. Underground and surface parking include EV charging points.', guest: 'Guest room', parking: 'Parking and charging',
    lobbyIndex: '05 · LOBBY', lobbyTitle: 'Light arrives first.', lobbyText: 'Spacious lobbies with stained-glass windows, soft lighting, a lift to the private courtyard and a barrier-free route.',
    locationIndex: '06 · LOCATION', locationTitle: 'Between Katta Darkhan and Akkurgan.', locationText: 'Mirzo-Ulugbek District, Tashkent. The project coordinates are confirmed by the project record.', coordinate: '41.332023° N · 69.307171° E',
    apartmentIndex: '07 · LIVE CATALOGUE', apartmentTitle: 'Find your rhythm.', apartmentText: '159 available residential entries in the fresh official snapshot. The source hides prices, so every price is shown on request.', rooms: 'rooms', floor: 'floor', phase: 'phase', request: 'On request', viewAll: 'View all apartments', askUnit: 'Ask about this apartment',
    contactIndex: '08 · CONSULTATION', contactTitle: 'Continue with a specific scenario.', contactText: 'Leave your name, phone, purchase goal and consent, and a TENCORP manager will prepare current options.', privacy: 'Personal data processing', disclaimer: 'All project imagery is CGI/render unless explicitly stated otherwise. Materials and the catalogue are not a public offer.', top: 'Back to top',
  },
} as const;

function apartmentRoomLabel(rooms: number, language: Language) {
  if (rooms === 0) return language === 'ru' ? 'Планировка' : language === 'uz' ? 'Reja' : 'Layout';
  if (language === 'en') return `${rooms} ${rooms === 1 ? 'room' : 'rooms'}`;
  return `${rooms} ${copy[language].rooms}`;
}

function Lightbox({ state, language, onClose }: { state: LightboxState; language: Language; onClose: () => void }) {
  const [index, setIndex] = useState(state.index); const panel = useRef<HTMLDivElement>(null); const close = useRef<HTMLButtonElement>(null); const pointer = useRef<{ id: number; x: number } | null>(null); const t = copy[language];
  const go = useCallback((delta: number) => setIndex((value) => (value + delta + gallery.length) % gallery.length), []);
  useEffect(() => { const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); else if (event.key === 'ArrowLeft') go(-1); else if (event.key === 'ArrowRight') go(1); else if (event.key === 'Tab' && panel.current) { const items = [...panel.current.querySelectorAll<HTMLElement>('button:not([tabindex="-1"])')]; const first = items[0]; const last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; window.addEventListener('keydown', key); return () => { document.body.style.overflow = overflow; window.removeEventListener('keydown', key); state.opener.focus(); }; }, [go, onClose, state.opener]);
  const slide = gallery[index];
  return <div className="sa-lightbox" role="dialog" aria-modal="true" aria-label={slide.title[language]}><button className="sa-lightbox__backdrop" type="button" tabIndex={-1} aria-label={t.closeImage} onClick={onClose} /><div className="sa-lightbox__panel" ref={panel}><header><span>{String(index + 1).padStart(2, '0')} {t.imageOf} {gallery.length}</span><button ref={close} type="button" onClick={onClose} aria-label={t.closeImage}>×</button></header><img src={asset(slide.src)} alt={`${slide.title[language]} · ${t.render}`} draggable={false} onPointerDown={(e) => { pointer.current = { id: e.pointerId, x: e.clientX }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerUp={(e) => { const start = pointer.current; pointer.current = null; if (start && start.id === e.pointerId && Math.abs(e.clientX - start.x) > 45) go(e.clientX < start.x ? 1 : -1); }} /><footer><div><strong>{slide.title[language]}</strong><p>{slide.text[language]}</p></div><nav><button type="button" onClick={() => go(-1)} aria-label={t.previous}>←</button><button type="button" onClick={() => go(1)} aria-label={t.next}>→</button></nav></footer></div></div>;
}

export function SaadiyatPage({ initialLanguage, previewUnits }: { initialLanguage: Language; previewUnits: Unit[] }) {
  const [menuOpen, setMenuOpen] = useState(false); const [galleryIndex, setGalleryIndex] = useState(0); const [lightbox, setLightbox] = useState<LightboxState>(); const [lead, setLead] = useState<{ surface: string; unit?: Unit; opener: HTMLElement | null }>(); const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const language = languageFrom(searchParams.get('lang'), initialLanguage); const galleryPointer = useRef<{ id: number; x: number } | null>(null); const menuRef = useRef<HTMLDivElement>(null); const menuButtonRef = useRef<HTMLButtonElement>(null); const t = copy[language];
  useSaadiyatDocumentLanguage(language);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .14 }); document.querySelectorAll('.sa-reveal').forEach((el) => observer.observe(el)); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!menuOpen) return; const overflow = document.body.style.overflow; const opener = menuButtonRef.current; document.body.style.overflow = 'hidden'; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') { e.preventDefault(); setMenuOpen(false); return; } if (e.key !== 'Tab' || !menuRef.current) return; const items = [...menuRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')]; const first = items[0]; const last = items.at(-1); if (!menuRef.current.contains(document.activeElement)) { e.preventDefault(); (e.shiftKey ? last : first)?.focus(); } else if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }; window.addEventListener('keydown', key); return () => { document.body.style.overflow = overflow; window.removeEventListener('keydown', key); window.requestAnimationFrame(() => opener?.focus({ preventScroll: true })); }; }, [menuOpen]);
  const changeLanguage = (next: Language) => { setMenuOpen(false); router.replace(`${pathname}?lang=${next}`, { scroll: false }); };
  const scroll = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const goGallery = (delta: number) => setGalleryIndex((value) => (value + delta + gallery.length) % gallery.length);
  const unitContext = (surface: string, unit?: Unit) => [`projectSlug=saadiyat`, `lang=${language}`, `surface=${surface}`, ...(unit ? [`unitId=${unit.id}`, `crmId=${unit.crmId}`, `number=${unit.number}`, `rooms=${unit.rooms}`, `area=${unit.area}`, `floor=${unit.floor}`, `section=${unit.section}`, `phase=${unit.phase}`] : ['unit=general'])].join(';');
  return <div className="sa-page" id="top">
    <a className="sa-skip" href="#content">{t.skip}</a>
    <header className="sa-header" aria-hidden={menuOpen || undefined} inert={menuOpen ? true : undefined}><a href={withLanguage('/saadiyat', language)} className="sa-brand"><img src={asset('/saadiyat/images/logo.webp')} alt="Saadiyat" /></a><nav aria-label={t.navLabel}>{t.nav.map(([id, label]) => <button key={id} type="button" onClick={() => scroll(id)}>{label}</button>)}</nav><div className="sa-header__actions"><div className="sa-lang" aria-label={language === 'ru' ? 'Язык' : language === 'uz' ? 'Til' : 'Language'}>{languages.map((item) => <button type="button" key={item} aria-pressed={item === language} className={item === language ? 'is-active' : ''} onClick={() => changeLanguage(item)}>{item.toUpperCase()}</button>)}</div><a href={withLanguage('/saadiyat/apartments', language)}>{t.choose}</a><button ref={menuButtonRef} className="sa-menu-trigger" type="button" aria-expanded={menuOpen} onClick={() => setMenuOpen(true)}>{t.menu}</button></div></header>
    {menuOpen ? <div className="sa-menu" ref={menuRef} role="dialog" aria-modal="true" aria-label={t.menu}><header><img src={asset('/saadiyat/images/logo.webp')} alt="Saadiyat" /><button type="button" autoFocus onClick={() => setMenuOpen(false)}>{t.close} ×</button></header><nav>{t.nav.map(([id, label], index) => <button type="button" key={id} onClick={() => scroll(id)}><small>0{index + 1}</small>{label}</button>)}</nav><footer><div>{languages.map((item) => <button type="button" key={item} className={item === language ? 'is-active' : ''} onClick={() => changeLanguage(item)}>{item.toUpperCase()}</button>)}</div><a href="tel:+998781137712">+998 78 113 77 12</a></footer></div> : null}
    <main id="content" aria-hidden={menuOpen || undefined} inert={menuOpen ? true : undefined}>
      <section className="sa-hero"><picture><source media="(max-width: 700px)" srcSet={asset('/saadiyat/images/hero-mobile.webp')} /><img src={asset('/saadiyat/images/hero.webp')} alt={`${t.heroTitle} ${t.render}`} /></picture><div className="sa-hero__veil" /><div className="sa-hero__content"><p>{t.overline}</p><h1>SAADIYAT</h1><h2>{t.heroTitle}</h2><p className="sa-hero__lead">{t.heroText}</p><div className="sa-hero__buttons"><a href={withLanguage('/saadiyat/apartments', language)}>{t.choose} <span>↗</span></a><button type="button" onClick={(e) => setLead({ surface: 'landing:hero', opener: e.currentTarget })}>{t.consult}</button></div></div><div className="sa-hero__caption">{t.render}</div><div className="sa-ripple" aria-hidden="true" /></section>
      <section className="sa-stats" aria-label="Facts">{t.stats.map(([value, label], index) => <div key={label} className="sa-reveal" style={{ transitionDelay: `${index * 70}ms` }}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section className="sa-idea sa-section" id="idea"><div className="sa-copy sa-reveal"><span>{t.ideaIndex}</span><h2>{t.ideaTitle}</h2><p>{t.ideaText}</p></div><figure className="sa-reveal"><img src={asset('/saadiyat/images/about.webp')} alt={`${t.ideaTitle} · ${t.render}`} loading="lazy" decoding="async" /><figcaption>{t.render}</figcaption></figure></section>
      <section className="sa-architecture sa-section" id="architecture"><div className="sa-copy sa-reveal"><span>{t.archIndex}</span><h2>{t.archTitle}</h2><p>{t.archText}</p></div><div className="sa-architecture__grid">{[['architecture-facade.webp', t.facade], ['architecture-entrance.webp', t.entrance], ['architecture-materials.webp', t.materials]].map(([src, label], index) => <figure className="sa-reveal" key={src}><img src={asset(`/saadiyat/images/${src}`)} alt={`${label} · ${t.render}`} loading="lazy" /><figcaption><b>0{index + 1}</b>{label}<small>{t.render}</small></figcaption></figure>)}</div></section>
      <section className="sa-island sa-section" id="island"><div className="sa-copy sa-reveal"><span>{t.islandIndex}</span><h2>{t.islandTitle}</h2><p>{t.islandText}</p></div><div className="sa-gallery sa-reveal" tabIndex={0} role="region" aria-label={t.islandTitle} onKeyDown={(e: ReactKeyboardEvent) => { if (e.key === 'ArrowLeft') goGallery(-1); if (e.key === 'ArrowRight') goGallery(1); }} onPointerDown={(e: ReactPointerEvent) => { galleryPointer.current = { id: e.pointerId, x: e.clientX }; }} onPointerUp={(e: ReactPointerEvent) => { const start = galleryPointer.current; galleryPointer.current = null; if (start && start.id === e.pointerId && Math.abs(e.clientX - start.x) > 45) goGallery(e.clientX < start.x ? 1 : -1); }}><button type="button" className="sa-gallery__image" onClick={(e) => setLightbox({ index: galleryIndex, opener: e.currentTarget })} aria-label={`${t.openImage}: ${gallery[galleryIndex].title[language]}`}><img src={asset(gallery[galleryIndex].src)} alt={`${gallery[galleryIndex].title[language]} · ${t.render}`} loading="lazy" /></button><div className="sa-gallery__info"><p><small>{String(galleryIndex + 1).padStart(2, '0')} / {gallery.length}</small><strong>{gallery[galleryIndex].title[language]}</strong><span>{gallery[galleryIndex].text[language]}</span></p><nav><button type="button" onClick={() => goGallery(-1)} aria-label={t.previous}>←</button><button type="button" onClick={() => goGallery(1)} aria-label={t.next}>→</button></nav></div></div></section>
      <section className="sa-community sa-section"><div className="sa-copy sa-reveal"><span>{t.communityIndex}</span><h2>{t.communityTitle}</h2><p>{t.communityText}</p></div><div className="sa-community__grid"><figure className="sa-reveal"><img src={asset('/saadiyat/images/guest-room.webp')} alt={`${t.guest} · ${t.render}`} loading="lazy" /><figcaption>{t.guest}<small>{t.render}</small></figcaption></figure><figure className="sa-reveal"><img src={asset('/saadiyat/images/parking.webp')} alt={`${t.parking} · ${t.render}`} loading="lazy" /><figcaption>{t.parking}<small>{t.render}</small></figcaption></figure></div></section>
      <section className="sa-lobby sa-section" id="lobby"><figure className="sa-reveal"><img src={asset('/saadiyat/images/lobby.webp')} alt={`${t.lobbyTitle} · ${t.render}`} loading="lazy" /><figcaption>{t.render}</figcaption></figure><div className="sa-copy sa-reveal"><span>{t.lobbyIndex}</span><h2>{t.lobbyTitle}</h2><p>{t.lobbyText}</p></div></section>
      <section className="sa-location sa-section" id="location"><div className="sa-copy sa-reveal"><span>{t.locationIndex}</span><h2>{t.locationTitle}</h2><p>{t.locationText}</p></div><div className="sa-location__map sa-reveal"><div className="sa-location__water" aria-hidden="true" /><span>SAADIYAT</span><strong>{t.coordinate}</strong><p>{language === 'ru' ? 'Ташкент · Мирзо-Улугбекский район' : language === 'uz' ? 'Toshkent · Mirzo Ulug‘bek tumani' : 'Tashkent · Mirzo-Ulugbek District'}</p></div></section>
      <section className="sa-apartments sa-section" id="apartments"><div className="sa-copy sa-reveal"><span>{t.apartmentIndex}</span><h2>{t.apartmentTitle}</h2><p>{t.apartmentText}</p></div><div className="sa-apartment-grid">{previewUnits.map((unit) => <article className="sa-unit sa-reveal" key={unit.id}><button type="button" className="sa-unit__plan" onClick={(e) => setLead({ surface: 'landing:preview', unit, opener: e.currentTarget })}><img src={asset(unit.plan)} alt={`${apartmentRoomLabel(unit.rooms, language)}, ${unit.area.toFixed(2)} m²`} loading="lazy" /></button><div><small>{unit.section} · {t.phase} {unit.phase}</small><h3>{apartmentRoomLabel(unit.rooms, language)} · {unit.area.toFixed(2)} m²</h3><p>№ {unit.number} · {unit.floor} {t.floor}</p><strong>{t.request}</strong><button type="button" onClick={(e) => setLead({ surface: 'landing:preview', unit, opener: e.currentTarget })}>{t.askUnit} ↗</button></div></article>)}</div><a className="sa-apartments__all" href={withLanguage('/saadiyat/apartments', language)}>{t.viewAll} <span>↗</span></a></section>
      <section className="sa-contact" id="contact"><div><span>{t.contactIndex}</span><h2>{t.contactTitle}</h2><p>{t.contactText}</p></div><button type="button" onClick={(e) => setLead({ surface: 'landing:contact', opener: e.currentTarget })}>{t.consult} <span>↗</span></button><a href="tel:+998781137712">{t.call}<strong>+998 78 113 77 12</strong></a></section>
    </main>
    <footer className="sa-footer" aria-hidden={menuOpen || undefined} inert={menuOpen ? true : undefined}><img src={asset('/saadiyat/images/logo.webp')} alt="Saadiyat" /><p>{t.disclaimer}</p><nav><a href={`${basePath}/privacy?project=saadiyat&lang=${language}&from=landing`}>{t.privacy}</a><a href="#top">{t.top} ↑</a></nav></footer>
    {lightbox ? <Lightbox state={lightbox} language={language} onClose={() => setLightbox(undefined)} /> : null}
    {lead ? <LeadModal open language={language} context={unitContext(lead.surface, lead.unit)} brandName="TENCORP" projectName="SAADIYAT" tagline={lead.unit ? `${apartmentRoomLabel(lead.unit.rooms, language)} · ${lead.unit.area.toFixed(2)} m² · № ${lead.unit.number}` : t.heroTitle} facts={lead.unit ? [`${lead.unit.section} · ${t.phase} ${lead.unit.phase}`, `${lead.unit.floor} ${t.floor}`, t.request] : t.leadFacts} submitUrl={saadiyatLeadSubmitUrl()} projectSlug="saadiyat" unitId={lead.unit?.id} unitKey={lead.unit ? `mbc-18:${lead.unit.id}` : undefined} privacyUrl={`${basePath}/privacy?project=saadiyat&lang=${language}&from=${encodeURIComponent(lead.surface)}`} requireConsent returnFocusTo={lead.opener} onClose={() => setLead(undefined)} /> : null}
  </div>;
}
