'use client';

/* eslint-disable @next/next/no-img-element */

import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useCallback, useEffect, useRef, useState } from 'react';
import { LeadModal, rememberLiveCatalogUnit } from '@/app/lead-modal';
import { catalogLeadIdentity, useLiveCatalogUnits } from '@/app/live-catalog';
import { useC1DocumentLanguage } from './c1-language';
import { c1LeadSubmitUrl } from './c1-lead';

type Language = 'ru' | 'uz' | 'en';
type Unit = { id: string | number; sourceKey?: string; number: string; rooms: number; area: number; floor: number; section: string; phase: string; completionYear: string; plan: string };
type Slide = { src: string; title: Record<Language, string>; text: Record<Language, string>; kind?: 'photo' | 'cgi' };
type LightboxState = { slides: Slide[]; index: number; opener: HTMLButtonElement };
const configuredBasePath = process.env.NEXT_PUBLIC_APP_BASE_PATH ?? '';
const basePath = configuredBasePath ? `/${configuredBasePath.replace(/^\/+|\/+$/g, '')}` : '';
const emptyPlanAsset = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 480"%3E%3Crect width="640" height="480" fill="%23f4eee4"/%3E%3Cpath d="M190 330V155h260v175M190 245h260M320 155v175M250 245v85M390 245v85" fill="none" stroke="%239c8061" stroke-width="8"/%3E%3C/svg%3E';
const asset = (value: string) => value ? `${basePath}${value}` : emptyPlanAsset;
const languageFrom = (value: string | null, fallback: Language): Language => value === 'ru' || value === 'uz' || value === 'en' ? value : fallback;
const languages: Language[] = ['ru', 'uz', 'en'];
const trackingKeys = ['tcid', 'fbclid'] as const;

const architecture: Slide[] = [
  { src: '/c1/images/architecture-01.webp', title: { ru: 'Строгая сетка', uz: 'Qat’iy to‘r', en: 'A disciplined grid' }, text: { ru: 'Геометричный фасад собирает башню в цельную городскую вертикаль.', uz: 'Geometrik fasad minorani yaxlit shahar vertikaliga birlashtiradi.', en: 'The geometric facade composes the tower as a single urban vertical.' } },
  { src: '/c1/images/architecture-02.webp', title: { ru: 'Панорамный свет', uz: 'Panoramali yorug‘lik', en: 'Panoramic light' }, text: { ru: 'Высокие окна усиливают вертикальный ритм и открывают город.', uz: 'Baland derazalar vertikal ritmni kuchaytirib, shaharni ochadi.', en: 'Tall windows intensify the vertical rhythm and open the city view.' } },
  { src: '/c1/images/architecture-03.webp', title: { ru: 'Городская доминанта', uz: 'Shahar dominantasi', en: 'An urban landmark' }, text: { ru: '30 этажей формируют заметный силуэт в центре Ташкента.', uz: '30 qavat Toshkent markazida yaqqol siluet yaratadi.', en: 'Thirty storeys create a distinct silhouette in central Tashkent.' } },
];

const amenities: Slide[] = [
  { src: '/c1/images/pool.webp', title: { ru: 'Открытый бассейн', uz: 'Ochiq basseyn', en: 'Open-air pool' }, text: { ru: 'Вода и lounge-пространство во внутренней среде дома.', uz: 'Uy ichki muhitida suv va lounge makoni.', en: 'Water and a lounge space within the residents’ environment.' } },
  { src: '/c1/images/guest-room.webp', title: { ru: 'Гостевая', uz: 'Mehmon xonasi', en: 'Guest room' }, text: { ru: 'Отдельное пространство для встреч и гостей.', uz: 'Uchrashuvlar va mehmonlar uchun alohida makon.', en: 'A separate space for meetings and guests.' } },
  { src: '/c1/images/kids.webp', title: { ru: 'Детская игровая', uz: 'Bolalar o‘yin xonasi', en: 'Children’s playroom' }, text: { ru: 'Защищённая игровая среда внутри комплекса.', uz: 'Majmua ichidagi himoyalangan o‘yin muhiti.', en: 'A protected play environment inside the complex.' } },
  { src: '/c1/images/fitness.webp', title: { ru: 'Общий fitness', uz: 'Umumiy fitness', en: 'Shared fitness' }, text: { ru: 'Тренировки становятся частью домашнего маршрута.', uz: 'Mashg‘ulotlar uy yo‘nalishining bir qismiga aylanadi.', en: 'Training becomes part of the daily route at home.' } },
  { src: '/c1/images/women-fitness.webp', title: { ru: 'Женский fitness', uz: 'Ayollar fitnessi', en: 'Women-only fitness' }, text: { ru: 'Самостоятельный зал для приватных тренировок.', uz: 'Maxfiy mashg‘ulotlar uchun alohida zal.', en: 'A separate room for private training.' } },
  { src: '/c1/images/stroller.webp', title: { ru: 'Колясочные', uz: 'Aravachalar xonasi', en: 'Stroller room' }, text: { ru: 'Повседневные вещи остаются вне квартиры.', uz: 'Kundalik buyumlar xonadondan tashqarida qoladi.', en: 'Everyday equipment stays outside the apartment.' } },
  { src: '/c1/images/massage.webp', title: { ru: 'Массажный кабинет', uz: 'Massaj xonasi', en: 'Massage room' }, text: { ru: 'Восстановление без лишней дороги по городу.', uz: 'Shahar bo‘ylab ortiqcha yo‘lsiz tiklanish.', en: 'Recovery without another trip across the city.' } },
  { src: '/c1/images/dry-clean.webp', title: { ru: 'Химчистка', uz: 'Kimyoviy tozalash', en: 'Dry cleaning' }, text: { ru: 'Бытовой сервис внутри жилой инфраструктуры.', uz: 'Turar joy infratuzilmasidagi maishiy xizmat.', en: 'A household service inside the residential infrastructure.' } },
  { src: '/c1/images/security.webp', title: { ru: 'Контроль доступа', uz: 'Kirish nazorati', en: 'Access control' }, text: { ru: 'Видеонаблюдение, контроль доступа и охрана.', uz: 'Videokuzatuv, kirish nazorati va qo‘riqlash.', en: 'Video surveillance, access control and security.' }, kind: 'photo' },
  { src: '/c1/images/parking.webp', title: { ru: 'Паркинг', uz: 'Parking', en: 'Parking' }, text: { ru: 'Автомобильная инфраструктура в контуре комплекса.', uz: 'Majmua hududidagi avtomobil infratuzilmasi.', en: 'Vehicle infrastructure within the complex.' } },
];

const copy = {
  ru: {
    leadFacts: ['Премиум', '30 этажей', 'I квартал 2028'] as const, skip: 'К содержанию', menu: 'Меню', close: 'Закрыть', navLabel: 'Навигация C1', nav: [['architecture', 'Архитектура'], ['location', 'Локация'], ['life', 'Среда'], ['lobby', 'Лобби'], ['apartments', 'Квартиры']] as const,
    choose: 'Выбрать квартиру', consult: 'Получить консультацию', call: 'Позвонить', overline: 'CENTER ONE · ПРЕМИУМ · ИДУТ ПРОДАЖИ', heroTitle: 'Vertical house', heroAccent: 'of light.', heroText: 'C1 — 30-этажная архитектурная доминанта с нью-йоркской строгостью фасада и панорамным светом.', status: 'Идут продажи', completion: 'Сдача · I квартал 2028', render: 'Официальная CGI-визуализация · проектный образ',
    stats: [['30', 'этажей'], ['252', 'квартиры'], ['1', 'блок'], ['4 300 м²', 'площадь проекта']] as const,
    architectureIndex: '01 · ВЕРТИКАЛЬ', architectureTitle: 'Свет поднимается по фасаду.', architectureText: 'Строгие линии, геометричная сетка и высокие панорамные окна переводят ритм Нью-Йорка в масштаб Ташкента.', openImage: 'Открыть изображение', previous: 'Предыдущее изображение', next: 'Следующее изображение', closeImage: 'Закрыть галерею', imageOf: 'из', cgi: 'CGI / проектный образ', photo: 'Иллюстративное фото · не стройка C1',
    locationIndex: '02 · ЦЕНТР ГОРОДА', locationTitle: 'Одна вертикаль. Весь город вокруг.', locationText: 'Яшнабадский район, улица С. Азимова, 46А. Координаты объекта подтверждены карточкой проекта.', coordinate: '41.307046° N · 69.292214° E', map: 'Открыть карту',
    lifeIndex: '03 · 10 СЦЕНАРИЕВ', lifeTitle: 'Дом продолжается за дверью квартиры.', lifeText: 'Бассейн и lounge, гостевая, игровые и wellness-пространства, сервис и безопасность — в одной вертикальной экосистеме.', scroll: 'Листайте',
    lobbyIndex: '04 · ЛОББИ', lobbyTitle: 'Мягкий свет. Никаких ступеней.', lobbyText: 'Витражные окна, скоростные лифты, металлические двери и безбарьерный доступ в приватный двор. Для посылок предусмотрены постаматы.', barrier: ['витражные окна', 'скоростные лифты', 'двор без ступеней', 'постаматы'] as const,
    apartmentIndex: '05 · КАТАЛОГ КВАРТИР', apartmentTitle: (count: number) => `${count} квартир в продаже. Цена — по запросу.`, apartmentText: 'Состав предложений обновляется автоматически. Выберите подходящую квартиру, а менеджер подтвердит актуальные условия.', rooms: 'комн.', floor: 'этаж', request: 'По запросу', viewAll: 'Открыть каталог', askUnit: 'Уточнить квартиру',
    contactIndex: '06 · КОНСУЛЬТАЦИЯ', contactTitle: 'Выберите высоту своего света.', contactText: 'Менеджер TENCORP проверит актуальную доступность и подготовит подборку. Заявка не является бронью.', privacy: 'Обработка персональных данных', disclaimer: 'Фасады, aerial, лобби, бассейн и интерьеры — CGI. Кадр безопасности — иллюстративное фото, не фиксация стройки C1. Материалы не являются публичной офертой.', top: 'Наверх', film: 'CGI-фильм проекта', filmHint: 'Без звука · проектный образ',
  },
  uz: {
    leadFacts: ['Premium', '30 qavat', '2028-yil I chorak'] as const, skip: 'Asosiy mazmunga', menu: 'Menyu', close: 'Yopish', navLabel: 'C1 navigatsiyasi', nav: [['architecture', 'Arxitektura'], ['location', 'Joylashuv'], ['life', 'Muhit'], ['lobby', 'Lobbi'], ['apartments', 'Xonadonlar']] as const,
    choose: 'Xonadon tanlash', consult: 'Maslahat olish', call: 'Qo‘ng‘iroq', overline: 'CENTER ONE · PREMIUM · SOTUVDA', heroTitle: 'Vertical house', heroAccent: 'of light.', heroText: 'C1 — Nyu-Yorkcha qat’iy fasad va panoramali yorug‘likka ega 30 qavatli arxitektura dominantasi.', status: 'Sotuvda', completion: 'Topshirish · 2028-yil I chorak', render: 'Rasmiy CGI-vizualizatsiya · loyiha obrazi',
    stats: [['30', 'qavat'], ['252', 'xonadon'], ['1', 'blok'], ['4 300 m²', 'loyiha maydoni']] as const,
    architectureIndex: '01 · VERTIKAL', architectureTitle: 'Yorug‘lik fasad bo‘ylab ko‘tariladi.', architectureText: 'Qat’iy chiziqlar, geometrik to‘r va baland panoramali derazalar Nyu-York ritmini Toshkent o‘lchamiga olib keladi.', openImage: 'Tasvirni ochish', previous: 'Oldingi tasvir', next: 'Keyingi tasvir', closeImage: 'Galereyani yopish', imageOf: 'dan', cgi: 'CGI / loyiha obrazi', photo: 'Illyustrativ foto · C1 qurilishi emas',
    locationIndex: '02 · SHAHAR MARKAZI', locationTitle: 'Bitta vertikal. Atrofda butun shahar.', locationText: 'Yashnobod tumani, S. Azimov ko‘chasi, 46A. Obyekt koordinatalari loyiha kartochkasida tasdiqlangan.', coordinate: '41.307046° N · 69.292214° E', map: 'Xaritani ochish',
    lifeIndex: '03 · 10 SSENARIY', lifeTitle: 'Uy xonadon eshigidan keyin ham davom etadi.', lifeText: 'Basseyn va lounge, mehmon, o‘yin va wellness makonlari, xizmat va xavfsizlik — yagona vertikal ekotizimda.', scroll: 'Surish',
    lobbyIndex: '04 · LOBBI', lobbyTitle: 'Yumshoq yorug‘lik. Zinapoyasiz.', lobbyText: 'Vitraj oynalar, tezkor liftlar, metall eshiklar va xususiy hovliga to‘siqsiz kirish. Jo‘natmalar uchun postamatlar ko‘zda tutilgan.', barrier: ['vitraj oynalar', 'tezkor liftlar', 'zinapoyasiz hovli', 'postamatlar'] as const,
    apartmentIndex: '05 · XONADON KATALOGI', apartmentTitle: (count: number) => `${count} ta xonadon sotuvda. Narx — so‘rov bo‘yicha.`, apartmentText: 'Takliflar tarkibi avtomatik yangilanadi. Mos xonadonni tanlang, menejer amaldagi shartlarni tasdiqlaydi.', rooms: 'xona', floor: 'qavat', request: 'So‘rov bo‘yicha', viewAll: 'Katalogni ochish', askUnit: 'Xonadonni aniqlash',
    contactIndex: '06 · MASLAHAT', contactTitle: 'O‘z yorug‘ligingiz balandligini tanlang.', contactText: 'TENCORP menejeri mavjudlikni tekshiradi va variantlarni tayyorlaydi. Ariza bron hisoblanmaydi.', privacy: 'Shaxsiy ma’lumotlarni qayta ishlash', disclaimer: 'Fasadlar, aerial, lobbi, basseyn va interyerlar — CGI. Xavfsizlik kadri illyustrativ foto, C1 qurilishi emas. Materiallar ommaviy oferta emas.', top: 'Yuqoriga', film: 'Loyiha CGI-filmi', filmHint: 'Ovozsiz · loyiha obrazi',
  },
  en: {
    leadFacts: ['Premium', '30 storeys', 'Q1 2028'] as const, skip: 'Skip to content', menu: 'Menu', close: 'Close', navLabel: 'C1 navigation', nav: [['architecture', 'Architecture'], ['location', 'Location'], ['life', 'Amenities'], ['lobby', 'Lobby'], ['apartments', 'Apartments']] as const,
    choose: 'Choose an apartment', consult: 'Request a consultation', call: 'Call', overline: 'CENTER ONE · PREMIUM · ON SALE', heroTitle: 'Vertical house', heroAccent: 'of light.', heroText: 'C1 is a 30-storey architectural landmark with a disciplined New York facade and panoramic light.', status: 'On sale', completion: 'Completion · Q1 2028', render: 'Official CGI visualisation · project concept',
    stats: [['30', 'storeys'], ['252', 'apartments'], ['1', 'block'], ['4,300 m²', 'project site']] as const,
    architectureIndex: '01 · THE VERTICAL', architectureTitle: 'Light climbs the facade.', architectureText: 'Strict lines, a geometric grid and tall panoramic windows translate New York rhythm into the scale of Tashkent.', openImage: 'Open image', previous: 'Previous image', next: 'Next image', closeImage: 'Close gallery', imageOf: 'of', cgi: 'CGI / project concept', photo: 'Illustrative photo · not C1 construction',
    locationIndex: '02 · CENTRAL CITY', locationTitle: 'One vertical. The whole city around it.', locationText: '46A S. Azimov Street, Yashnabad District. The project coordinates are confirmed in the project record.', coordinate: '41.307046° N · 69.292214° E', map: 'Open map',
    lifeIndex: '03 · 10 SCENARIOS', lifeTitle: 'Home continues beyond the apartment door.', lifeText: 'Pool and lounge, guest, play and wellness spaces, service and security — within one vertical ecosystem.', scroll: 'Scroll',
    lobbyIndex: '04 · LOBBY', lobbyTitle: 'Soft light. No steps.', lobbyText: 'Stained-glass windows, high-speed lifts, metal doors and barrier-free access to the private courtyard. Parcel lockers are provided.', barrier: ['stained-glass windows', 'high-speed lifts', 'step-free courtyard', 'parcel lockers'] as const,
    apartmentIndex: '05 · APARTMENT CATALOGUE', apartmentTitle: (count: number) => `${count} apartments on sale. Price on request.`, apartmentText: 'Listings update automatically. Choose an apartment and a manager will confirm the current terms.', rooms: 'rooms', floor: 'floor', request: 'On request', viewAll: 'Open catalogue', askUnit: 'Ask about this apartment',
    contactIndex: '06 · CONSULTATION', contactTitle: 'Choose the height of your light.', contactText: 'A TENCORP manager will re-check availability and prepare options. A request is not a reservation.', privacy: 'Personal data processing', disclaimer: 'Facades, aerial, lobby, pool and interiors are CGI. The security frame is an illustrative photograph, not C1 construction evidence. Materials are not a public offer.', top: 'Back to top', film: 'Project CGI film', filmHint: 'Muted · project concept',
  },
} as const;

function roomLabel(rooms: number, language: Language) { return language === 'en' ? `${rooms} ${rooms === 1 ? 'room' : 'rooms'}` : `${rooms} ${copy[language].rooms}`; }
function planMissingLabel(language: Language) { return language === 'ru' ? 'Планировка пока недоступна' : language === 'uz' ? 'Reja hozircha mavjud emas' : 'Floor plan is not available yet'; }

function isolateBackground(selector: string) {
  const elements = [...document.querySelectorAll<HTMLElement>(selector)];
  const previous = elements.map((element) => ({ inert: element.hasAttribute('inert'), ariaHidden: element.getAttribute('aria-hidden') }));
  elements.forEach((element) => { element.setAttribute('inert', ''); element.setAttribute('aria-hidden', 'true'); });
  return () => elements.forEach((element, index) => { if (!previous[index].inert) element.removeAttribute('inert'); if (previous[index].ariaHidden === null) element.removeAttribute('aria-hidden'); else element.setAttribute('aria-hidden', previous[index].ariaHidden!); });
}

function Lightbox({ state, language, onClose }: { state: LightboxState; language: Language; onClose: () => void }) {
  const [index, setIndex] = useState(state.index); const panel = useRef<HTMLDivElement>(null); const close = useRef<HTMLButtonElement>(null); const pointer = useRef<{ id: number; x: number } | null>(null); const t = copy[language];
  const go = useCallback((delta: number) => setIndex((value) => (value + delta + state.slides.length) % state.slides.length), [state.slides.length]);
  useEffect(() => { const overflow = document.body.style.overflow; const restoreBackground = isolateBackground('.c1-site > header, .c1-site > main'); document.body.style.overflow = 'hidden'; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); event.stopImmediatePropagation(); onClose(); } else if (event.key === 'ArrowLeft') go(-1); else if (event.key === 'ArrowRight') go(1); else if (event.key === 'Tab' && panel.current) { const items = [...panel.current.querySelectorAll<HTMLElement>('button:not([disabled])')]; const first = items[0]; const last = items.at(-1); if (!panel.current.contains(document.activeElement)) { event.preventDefault(); (event.shiftKey ? last : first)?.focus(); } else if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; window.addEventListener('keydown', key); return () => { document.body.style.overflow = overflow; restoreBackground(); window.removeEventListener('keydown', key); window.requestAnimationFrame(() => state.opener.isConnected && state.opener.focus({ preventScroll: true })); }; }, [go, onClose, state.opener]);
  const slide = state.slides[index];
  return <div className="c1-lightbox" role="dialog" aria-modal="true" aria-label={slide.title[language]}><button className="c1-lightbox__backdrop" type="button" tabIndex={-1} aria-label={t.closeImage} onClick={onClose} /><div className="c1-lightbox__panel" ref={panel}><header><span>{String(index + 1).padStart(2, '0')} {t.imageOf} {state.slides.length}</span><strong>{slide.kind === 'photo' ? t.photo : t.cgi}</strong><button ref={close} type="button" onClick={onClose} aria-label={t.closeImage}>×</button></header><img src={asset(slide.src)} alt={`${slide.title[language]} · ${slide.kind === 'photo' ? t.photo : t.cgi}`} draggable={false} onPointerDown={(event) => { pointer.current = { id: event.pointerId, x: event.clientX }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={(event) => { const start = pointer.current; pointer.current = null; if (start && start.id === event.pointerId && Math.abs(event.clientX - start.x) > 44) go(event.clientX < start.x ? 1 : -1); }} /><footer><div><h2>{slide.title[language]}</h2><p>{slide.text[language]}</p></div><nav><button type="button" onClick={() => go(-1)} aria-label={t.previous}>←</button><button type="button" onClick={() => go(1)} aria-label={t.next}>→</button></nav></footer></div></div>;
}

export function C1Page({ initialLanguage, previewUnits: embeddedPreviewUnits, initialAvailableCount }: { initialLanguage: Language; previewUnits: Unit[]; initialAvailableCount: number }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const language = languageFrom(params.get('lang'), initialLanguage); const t = copy[language]; const [menuOpen, setMenuOpen] = useState(false); const [amenityIndex, setAmenityIndex] = useState(0); const [lightbox, setLightbox] = useState<LightboxState>(); const [lead, setLead] = useState<{ surface: string; unit?: Unit; opener: HTMLElement | null }>(); const menu = useRef<HTMLDivElement>(null); const menuButton = useRef<HTMLButtonElement>(null); const rail = useRef<HTMLDivElement>(null); const heroImage = useRef<HTMLPictureElement>(null);
  const { data: liveUnits, project } = useLiveCatalogUnits('c1', embeddedPreviewUnits);
  const previewUnits = liveUnits.slice(0, 4);
  const availableCount = project?.availableUnits ?? initialAvailableCount;
  useC1DocumentLanguage(language);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .12 }); document.querySelectorAll('.c1-reveal').forEach((element) => observer.observe(element)); return () => observer.disconnect(); }, []);
  useEffect(() => { const reduced = matchMedia('(prefers-reduced-motion: reduce)'); if (reduced.matches) return; const move = () => { const y = Math.min(window.scrollY * .1, 70); if (heroImage.current) heroImage.current.style.transform = `translate3d(0,${y}px,0) scale(1.035)`; }; move(); window.addEventListener('scroll', move, { passive: true }); return () => window.removeEventListener('scroll', move); }, []);
  useEffect(() => { if (!menuOpen) return; const old = document.body.style.overflow; const opener = menuButton.current; const background = [...document.querySelectorAll<HTMLElement>('.c1-header, main#content')]; document.body.style.overflow = 'hidden'; background.forEach((element) => { element.setAttribute('inert', ''); element.setAttribute('aria-hidden', 'true'); }); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); setMenuOpen(false); return; } if (event.key !== 'Tab' || !menu.current) return; const items = [...menu.current.querySelectorAll<HTMLElement>('button,a[href]')]; const first = items[0]; const last = items.at(-1); if (!menu.current.contains(document.activeElement)) { event.preventDefault(); (event.shiftKey ? last : first)?.focus(); } else if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; window.addEventListener('keydown', onKey); menu.current?.querySelector<HTMLElement>('button')?.focus(); return () => { document.body.style.overflow = old; background.forEach((element) => { element.removeAttribute('inert'); element.removeAttribute('aria-hidden'); }); window.removeEventListener('keydown', onKey); opener?.focus(); }; }, [menuOpen]);
  const queryFor = (next: Language) => { const query = new URLSearchParams(); query.set('lang', next); params.forEach((value, key) => { if (key.startsWith('utm_') || trackingKeys.includes(key as (typeof trackingKeys)[number])) query.append(key, value); }); return query.toString(); };
  const trackedLink = (value: string, next: Language = language) => `${basePath}${value}?${queryFor(next)}`;
  const changeLanguage = (next: Language) => { router.replace(`${pathname}?${queryFor(next)}`, { scroll: false }); setMenuOpen(false); };
  const openLightbox = (slides: Slide[], index: number, opener: HTMLButtonElement) => setLightbox({ slides, index, opener });
  const moveAmenity = (delta: number) => { const next = (amenityIndex + delta + amenities.length) % amenities.length; setAmenityIndex(next); rail.current?.children[next]?.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' }); };
  useEffect(() => { if (!lead) return; return isolateBackground('.c1-site > header, .c1-site > main'); }, [lead]);
  const openLead = (surface: string, opener: HTMLElement | null, unit?: Unit) => { if (unit) rememberLiveCatalogUnit(unit, 'c1'); setLead({ surface, unit, opener }); };
  const leadIdentity = catalogLeadIdentity(lead?.unit);
  const leadContext = (surface: string, unit?: Unit) => [`projectSlug=c1`, `lang=${language}`, `surface=landing:${surface}`, ...(unit ? [...(leadIdentity.unitKey ? [`unitKey=${leadIdentity.unitKey}`] : []), `number=${unit.number}`, `rooms=${unit.rooms}`, `area=${unit.area}`, `floor=${unit.floor}`, `section=${unit.section}`, `phase=${unit.phase}`, `completion=${unit.completionYear}`] : ['unit=general'])].join(';');
  return <div className="c1-site" id="top"><a className="c1-skip" href="#content">{t.skip}</a><header className="c1-header"><a className="c1-brand" href={trackedLink('/c1')} aria-label="C1"><img src={asset('/c1/images/logo.webp')} alt="C1" /></a><nav aria-label={t.navLabel}>{t.nav.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="c1-header__actions"><a href="tel:+998781137712">+998 78 113 77 12</a><button type="button" onClick={(event) => openLead('header', event.currentTarget)}>{t.consult}</button><button ref={menuButton} className="c1-menu-button" type="button" aria-expanded={menuOpen} onClick={() => setMenuOpen(true)}>{t.menu}</button></div></header>
    {menuOpen ? <div className="c1-menu" role="dialog" aria-modal="true" aria-label={t.navLabel} ref={menu}><header><img src={asset('/c1/images/logo.webp')} alt="C1" /><button type="button" onClick={() => setMenuOpen(false)}>{t.close} ×</button></header><nav>{t.nav.map(([id, label], index) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}><span>0{index + 1}</span>{label}</a>)}</nav><footer>{languages.map((item) => <button type="button" key={item} className={item === language ? 'is-active' : ''} onClick={() => changeLanguage(item)}>{item.toUpperCase()}</button>)}</footer></div> : null}
    <main id="content"><section className="c1-hero"><picture ref={heroImage}><source media="(max-width: 650px)" srcSet={asset('/c1/images/hero-mobile.webp')} /><img src={asset('/c1/images/hero.webp')} alt={`${t.heroTitle} ${t.heroAccent} · ${t.render}`} /></picture><div className="c1-hero__shade" /><div className="c1-index" aria-hidden="true">C1</div><div className="c1-hero__copy"><span>{t.overline}</span><h1>{t.heroTitle}<em>{t.heroAccent}</em></h1><p>{t.heroText}</p><button type="button" onClick={(event) => openLead('hero', event.currentTarget)}>{t.consult} ↗</button></div><dl>{t.stats.map(([value, label]) => <div key={label}><dt>{value}</dt><dd>{label}</dd></div>)}</dl><aside><span>{t.status}</span><strong>{t.completion}</strong></aside><small className="c1-media-label">{t.render}</small></section>
      <section className="c1-architecture" id="architecture"><header className="c1-reveal"><span>{t.architectureIndex}</span><h2>{t.architectureTitle}</h2><p>{t.architectureText}</p></header><div className="c1-architecture__grid">{architecture.map((slide, index) => <button className="c1-reveal" type="button" key={slide.src} onClick={(event) => openLightbox(architecture, index, event.currentTarget)} aria-label={`${t.openImage}: ${slide.title[language]}`}><img src={asset(slide.src)} alt={`${slide.title[language]} · ${t.cgi}`} loading="lazy" /><span><small>{t.cgi}</small><strong>{slide.title[language]}</strong><i>↗</i></span></button>)}</div><div className="c1-floor-story" aria-label="30 storeys">{[6, 12, 18, 24, 30].map((floor) => <span key={floor}><b>{String(floor).padStart(2, '0')}</b><i /></span>)}</div></section>
      <section className="c1-location" id="location"><figure className="c1-reveal"><img src={asset('/c1/images/aerial.webp')} alt={`${t.locationTitle} · ${t.cgi}`} loading="lazy" /><figcaption>{t.cgi}</figcaption></figure><article className="c1-reveal"><span>{t.locationIndex}</span><h2>{t.locationTitle}</h2><p>{t.locationText}</p><strong>{t.coordinate}</strong><a href="https://www.google.com/maps/search/?api=1&query=41.307046%2C69.292214" target="_blank" rel="noreferrer">{t.map} ↗</a></article></section>
      <section className="c1-life" id="life"><header className="c1-reveal"><span>{t.lifeIndex}</span><h2>{t.lifeTitle}</h2><p>{t.lifeText}</p><nav><small>{t.scroll}</small><button type="button" onClick={() => moveAmenity(-1)} aria-label={t.previous}>←</button><button type="button" onClick={() => moveAmenity(1)} aria-label={t.next}>→</button></nav></header><div className="c1-life__rail" ref={rail} tabIndex={0} onKeyDown={(event) => { if (event.key === 'ArrowLeft') moveAmenity(-1); if (event.key === 'ArrowRight') moveAmenity(1); }} onScroll={(event) => { const cards = [...event.currentTarget.children] as HTMLElement[]; const center = event.currentTarget.scrollLeft + event.currentTarget.clientWidth / 2; let nearest = 0; cards.forEach((card, index) => { if (Math.abs(card.offsetLeft + card.offsetWidth / 2 - center) < Math.abs(cards[nearest].offsetLeft + cards[nearest].offsetWidth / 2 - center)) nearest = index; }); setAmenityIndex(nearest); }}>{amenities.map((slide, index) => <button type="button" key={slide.src} onClick={(event) => openLightbox(amenities, index, event.currentTarget)} className={amenityIndex === index ? 'is-active' : ''} aria-label={`${t.openImage}: ${slide.title[language]}`}><img src={asset(slide.src)} alt={`${slide.title[language]} · ${slide.kind === 'photo' ? t.photo : t.cgi}`} loading="lazy" /><span><small>{slide.kind === 'photo' ? t.photo : t.cgi}</small><b>{String(index + 1).padStart(2, '0')}</b><strong>{slide.title[language]}</strong><p>{slide.text[language]}</p></span></button>)}</div></section>
      <section className="c1-lobby" id="lobby"><article className="c1-reveal"><span>{t.lobbyIndex}</span><h2>{t.lobbyTitle}</h2><p>{t.lobbyText}</p><ul>{t.barrier.map((item, index) => <li key={item}><span>0{index + 1}</span>{item}</li>)}</ul></article><figure className="c1-reveal"><img src={asset('/c1/images/lobby.webp')} alt={`${t.lobbyTitle} · ${t.cgi}`} loading="lazy" /><figcaption>{t.cgi}</figcaption></figure></section>
      <section className="c1-film"><video controls muted playsInline preload="metadata" poster={asset('/c1/images/architecture-02.webp')} aria-label={t.film}><source src={asset('/c1/video/c1-film.mp4')} type="video/mp4" /></video><div><span>{t.film}</span><strong>{t.filmHint}</strong></div></section>
      <section className="c1-apartments" id="apartments"><header className="c1-reveal"><span>{t.apartmentIndex}</span><h2>{t.apartmentTitle(availableCount)}</h2><p>{t.apartmentText}</p><a href={trackedLink('/c1/apartments')}>{t.viewAll} ↗</a></header><div>{previewUnits.map((unit) => <article key={unit.id} className="c1-reveal">{unit.plan ? <img src={asset(unit.plan)} alt={`${roomLabel(unit.rooms, language)} №${unit.number}`} loading="lazy" /> : <div className="c1-apartments__plan-missing" role="img" aria-label={planMissingLabel(language)}>{planMissingLabel(language)}</div>}<small>{t.floor} {unit.floor} · № {unit.number}</small><h3>{roomLabel(unit.rooms, language)}</h3><dl><div><dt>m²</dt><dd>{unit.area.toFixed(2)}</dd></div><div><dt>{t.request}</dt><dd>—</dd></div></dl><button type="button" onClick={(event) => openLead('preview-card', event.currentTarget, unit)}>{t.askUnit} ↗</button></article>)}</div></section>
      <section className="c1-contact" id="contact"><div className="c1-contact__index" aria-hidden="true">30</div><article className="c1-reveal"><span>{t.contactIndex}</span><h2>{t.contactTitle}</h2><p>{t.contactText}</p><button type="button" onClick={(event) => openLead('contact', event.currentTarget)}>{t.consult} ↗</button></article><a href="tel:+998781137712">+998 78 113 77 12</a><footer><img src={asset('/c1/images/logo.webp')} alt="C1" /><p>{t.disclaimer}</p><nav><a href={`${basePath}/privacy?project=c1&lang=${language}&from=landing`}>{t.privacy}</a><button type="button" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>{t.top} ↑</button></nav></footer></section>
    </main>{lightbox ? <Lightbox state={lightbox} language={language} onClose={() => setLightbox(undefined)} /> : null}{lead ? <LeadModal open language={language} context={leadContext(lead.surface, lead.unit)} brandName="TENCORP" projectName="C1" tagline={lead.unit ? `${roomLabel(lead.unit.rooms, language)} · ${lead.unit.area.toFixed(2)} m² · № ${lead.unit.number}` : t.heroAccent} facts={lead.unit ? [`${t.floor} ${lead.unit.floor}`, `${lead.unit.area.toFixed(2)} m²`, t.request] : t.leadFacts} submitUrl={c1LeadSubmitUrl()} projectSlug="c1" {...leadIdentity} privacyUrl={`${basePath}/privacy?project=c1&lang=${language}&from=landing-${encodeURIComponent(lead.surface)}`} requireConsent returnFocusTo={lead.opener} onClose={() => setLead(undefined)} /> : null}</div>;
}
